// packages/react/src/components/app/Button.tsx
import type { ReactNode, MouseEvent as ReactMouseEvent, CSSProperties } from 'react';

export type ButtonVariant = 'primary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface ButtonProps {
  children: ReactNode;
  variant?: ButtonVariant;
  /** Hex accent color override. Used as the bg on `primary`, the text on `ghost`. Defaults to `var(--color-fg)`. */
  accent?: string;
  size?: ButtonSize;
  icon?: ReactNode;
  trailingIcon?: ReactNode;
  loading?: boolean;
  fullWidth?: boolean;
  disabled?: boolean;
  className?: string;
  style?: CSSProperties;
  /** Render as an `<a>` instead of a `<button>`. Requires `href`. */
  as?: 'button' | 'a';
  href?: string;
  target?: string;
  rel?: string;
  type?: 'button' | 'submit' | 'reset';
  onClick?: (e: ReactMouseEvent<HTMLButtonElement | HTMLAnchorElement>) => void;
  'aria-label'?: string;
}

const sizeMap: Record<
  ButtonSize,
  { padding: string; fontSize: number; gap: number; radius: number }
> = {
  sm: { padding: '5px 10px', fontSize: 11, gap: 6, radius: 6 },
  md: { padding: '8px 14px', fontSize: 12, gap: 8, radius: 8 },
  lg: { padding: '12px 20px', fontSize: 14, gap: 10, radius: 10 },
};

/**
 * Editorial app button — mono label, accent-filled (primary), ghost-bordered,
 * or danger (red). Sizes sm/md/lg, optional loading spinner, optional anchor
 * via `as="a"`. Same DM-Mono + var(--color-fg) tokens as the rest of the
 * editorial bundle.
 */
export function Button({
  children,
  variant = 'primary',
  accent,
  size = 'md',
  icon,
  trailingIcon,
  loading = false,
  fullWidth = false,
  disabled,
  className,
  style,
  as,
  href,
  target,
  rel,
  type,
  onClick,
  'aria-label': ariaLabel,
}: ButtonProps) {
  const isPrimary = variant === 'primary';
  const isDanger = variant === 'danger';
  const dangerColor = '#dc2626';

  let bg: string;
  let fg: string;
  let border: string;
  if (isDanger) {
    bg = accent ?? dangerColor;
    fg = '#fff';
    border = bg;
  } else if (isPrimary) {
    bg = accent ?? 'var(--color-fg)';
    fg = '#fff';
    border = bg;
  } else {
    bg = 'transparent';
    fg = accent ?? 'var(--color-fg)';
    border = 'var(--color-rule-strong)';
  }

  const dim = sizeMap[size];
  const isInactive = Boolean(disabled || loading);

  const sharedStyle: CSSProperties = {
    padding: dim.padding,
    borderRadius: dim.radius,
    fontSize: dim.fontSize,
    letterSpacing: '0.04em',
    border: `1px solid ${border}`,
    background: bg,
    color: fg,
    cursor: isInactive ? 'not-allowed' : 'pointer',
    opacity: isInactive ? 0.55 : 1,
    display: fullWidth ? 'flex' : 'inline-flex',
    width: fullWidth ? '100%' : undefined,
    alignItems: 'center',
    justifyContent: 'center',
    gap: dim.gap,
    textDecoration: 'none',
    transition: 'background 160ms ease-out, opacity 160ms, box-shadow 160ms',
    ...style,
  };

  const content = (
    <>
      {loading ? (
        <span
          aria-hidden
          style={{
            width: dim.fontSize,
            height: dim.fontSize,
            border: `1.5px solid ${fg}`,
            borderRightColor: 'transparent',
            borderRadius: '50%',
            display: 'inline-block',
            animation: 'ferrlabs-spin 700ms linear infinite',
          }}
        />
      ) : (
        icon && <span aria-hidden>{icon}</span>
      )}
      {children}
      {!loading && trailingIcon && <span aria-hidden>{trailingIcon}</span>}
      <style>{`@keyframes ferrlabs-spin { to { transform: rotate(360deg); } }`}</style>
    </>
  );

  if (as === 'a' && href) {
    return (
      <a
        href={href}
        target={target}
        rel={rel}
        onClick={onClick as React.MouseEventHandler<HTMLAnchorElement>}
        className={['mono', className].filter(Boolean).join(' ')}
        style={sharedStyle}
        aria-label={ariaLabel}
        aria-disabled={isInactive || undefined}
      >
        {content}
      </a>
    );
  }

  return (
    <button
      type={type ?? 'button'}
      onClick={onClick as React.MouseEventHandler<HTMLButtonElement>}
      disabled={isInactive}
      aria-busy={loading || undefined}
      aria-label={ariaLabel}
      className={['mono', className].filter(Boolean).join(' ')}
      style={sharedStyle}
    >
      {content}
    </button>
  );
}

// packages/ui-ng/src/lib/button/button.component.ts
import { NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';

export type ButtonVariant = 'primary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';

interface SizeDim {
  readonly padding: string;
  readonly fontSize: string;
  readonly gap: string;
  readonly radius: string;
}

const SIZE: Record<ButtonSize, SizeDim> = {
  sm: { padding: '5px 10px', fontSize: '11px', gap: '6px', radius: '6px' },
  md: { padding: '8px 14px', fontSize: '12px', gap: '8px', radius: '8px' },
  lg: { padding: '12px 20px', fontSize: '14px', gap: '10px', radius: '10px' },
};

const DANGER = '#dc2626';

/**
 * Editorial app button — Angular 22 port of `@ferrlabs/ui-react`'s Button.
 * Mono label, accent-filled (primary), ghost-bordered, or danger. Renders an
 * `<a>` when `href` is set, otherwise a `<button>`. Styling reads the shared
 * tokens from `@ferrlabs/ui-foundation` (`--color-accent`, `--color-fg`,
 * `--color-rule-strong`, `--font-mono`).
 */
@Component({
  selector: 'flr-button',
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (href(); as link) {
      <a
        class="flr-btn"
        [href]="link"
        [attr.target]="target()"
        [attr.rel]="rel()"
        [attr.aria-label]="ariaLabel()"
        [attr.aria-disabled]="inactive() || null"
        [style]="styles()"
        (click)="handleClick($event)"
      >
        <ng-container [ngTemplateOutlet]="body" />
      </a>
    } @else {
      <button
        class="flr-btn"
        [type]="type()"
        [disabled]="inactive()"
        [attr.aria-busy]="loading() || null"
        [attr.aria-label]="ariaLabel()"
        [style]="styles()"
        (click)="handleClick($event)"
      >
        <ng-container [ngTemplateOutlet]="body" />
      </button>
    }

    <ng-template #body>
      @if (loading()) {
        <span
          class="flr-btn__spinner"
          aria-hidden="true"
          [style.width]="dim().fontSize"
          [style.height]="dim().fontSize"
        ></span>
      }
      <ng-content />
    </ng-template>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-btn {
      font-family: var(--font-mono);
      letter-spacing: 0.04em;
      align-items: center;
      justify-content: center;
      text-decoration: none;
      cursor: pointer;
      transition: background 160ms ease-out, opacity 160ms, box-shadow 160ms;
    }
    .flr-btn:disabled,
    .flr-btn[aria-disabled='true'] {
      cursor: not-allowed;
      opacity: 0.55;
    }
    .flr-btn__spinner {
      border: 1.5px solid currentColor;
      border-right-color: transparent;
      border-radius: 50%;
      display: inline-block;
      animation: flr-btn-spin 700ms linear infinite;
    }
    @keyframes flr-btn-spin {
      to {
        transform: rotate(360deg);
      }
    }
  `,
})
export class ButtonComponent {
  readonly variant = input<ButtonVariant>('primary');
  readonly size = input<ButtonSize>('md');
  /** Hex accent override. Bg on `primary`/`danger`, text on `ghost`. */
  readonly accent = input<string | null>(null);
  readonly loading = input(false);
  readonly fullWidth = input(false);
  readonly disabled = input(false);
  readonly type = input<'button' | 'submit' | 'reset'>('button');
  readonly href = input<string | null>(null);
  readonly target = input<string | null>(null);
  readonly rel = input<string | null>(null);
  readonly ariaLabel = input<string | null>(null, { alias: 'aria-label' });

  readonly pressed = output<MouseEvent>();

  protected readonly inactive = computed(() => this.disabled() || this.loading());
  protected readonly dim = computed(() => SIZE[this.size()]);

  protected readonly styles = computed<Record<string, string | null>>(() => {
    const accent = this.accent();
    let bg: string;
    let fg: string;
    let border: string;
    switch (this.variant()) {
      case 'danger':
        bg = accent ?? DANGER;
        fg = '#fff';
        border = bg;
        break;
      case 'ghost':
        bg = 'transparent';
        fg = accent ?? 'var(--color-fg)';
        border = 'var(--color-rule-strong)';
        break;
      default:
        bg = accent ?? 'var(--color-accent, var(--color-fg))';
        fg = '#fff';
        border = bg;
    }
    const d = this.dim();
    return {
      display: this.fullWidth() ? 'flex' : 'inline-flex',
      width: this.fullWidth() ? '100%' : null,
      padding: d.padding,
      'border-radius': d.radius,
      'font-size': d.fontSize,
      gap: d.gap,
      border: `1px solid ${border}`,
      background: bg,
      color: fg,
    };
  });

  protected handleClick(event: MouseEvent): void {
    if (this.inactive()) {
      event.preventDefault();
      event.stopImmediatePropagation();
      return;
    }
    this.pressed.emit(event);
  }
}
