// packages/primitives/src/Radio.tsx
import {
  createContext,
  forwardRef,
  useContext,
  useId,
  useState,
  type CSSProperties,
  type InputHTMLAttributes,
  type ReactNode,
} from 'react';

interface RadioGroupContextValue {
  name: string;
  value?: string | number;
  onChange?: (value: string) => void;
  disabled?: boolean;
}

const RadioGroupContext = createContext<RadioGroupContextValue | null>(null);

export interface RadioGroupProps {
  name?: string;
  value?: string | number;
  onChange?: (value: string) => void;
  disabled?: boolean;
  children: ReactNode;
  orientation?: 'vertical' | 'horizontal';
  className?: string;
  ariaLabel?: string;
}

export function RadioGroup({
  name,
  value,
  onChange,
  disabled,
  children,
  orientation = 'vertical',
  className,
  ariaLabel,
}: RadioGroupProps) {
  const fallbackName = useId();
  return (
    <RadioGroupContext.Provider value={{ name: name ?? fallbackName, value, onChange, disabled }}>
      <div
        role="radiogroup"
        aria-label={ariaLabel}
        className={className}
        style={{
          display: 'flex',
          flexDirection: orientation === 'vertical' ? 'column' : 'row',
          gap: orientation === 'vertical' ? 10 : 16,
        }}
      >
        {children}
      </div>
    </RadioGroupContext.Provider>
  );
}

export interface RadioProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type' | 'value' | 'children'
> {
  value: string | number;
  label?: ReactNode;
  hint?: ReactNode;
  invalid?: boolean;
}

export const Radio = forwardRef<HTMLInputElement, RadioProps>(function Radio(
  { value, label, hint, invalid, className, style, disabled, id, onFocus, onBlur, ...rest },
  ref,
) {
  const ctx = useContext(RadioGroupContext);
  const checked = ctx?.value !== undefined ? String(ctx.value) === String(value) : undefined;
  const isDisabled = disabled || ctx?.disabled;
  const [focused, setFocused] = useState(false);

  const accent = 'var(--color-accent, var(--color-ink))';
  const errorColor = '#dc2626';
  const borderColor = invalid ? errorColor : checked ? accent : 'var(--color-rule-strong)';

  const boxStyle: CSSProperties = {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 16,
    height: 16,
    flexShrink: 0,
    borderRadius: 999,
    background: isDisabled ? 'var(--color-paper-2)' : 'var(--color-card)',
    border: `1px solid ${borderColor}`,
    boxShadow: focused
      ? `0 0 0 3px color-mix(in oklab, ${invalid ? '#dc2626' : 'var(--color-accent, var(--color-ink))'} 30%, transparent)`
      : undefined,
    transition: 'border-color 140ms, box-shadow 140ms',
    cursor: isDisabled ? 'not-allowed' : 'pointer',
    opacity: isDisabled ? 0.55 : 1,
  };

  const inputStyle: CSSProperties = {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    margin: 0,
    opacity: 0,
    cursor: isDisabled ? 'not-allowed' : 'pointer',
  };

  const dotStyle: CSSProperties = {
    width: 8,
    height: 8,
    borderRadius: 999,
    background: accent,
    opacity: checked ? 1 : 0,
    transition: 'opacity 120ms',
    pointerEvents: 'none',
  };

  const inputElement = (
    <span style={boxStyle}>
      <input
        ref={ref}
        id={id}
        type="radio"
        name={ctx?.name}
        value={value}
        checked={checked}
        disabled={isDisabled}
        onChange={(e) => ctx?.onChange?.(e.currentTarget.value)}
        onFocus={(e) => {
          setFocused(true);
          onFocus?.(e);
        }}
        onBlur={(e) => {
          setFocused(false);
          onBlur?.(e);
        }}
        style={inputStyle}
        aria-invalid={invalid || undefined}
        {...rest}
      />
      <span aria-hidden style={dotStyle} />
    </span>
  );

  if (!label && !hint) {
    return (
      <span className={className} style={style}>
        {inputElement}
      </span>
    );
  }

  return (
    <label
      className={className}
      style={{
        display: 'inline-flex',
        alignItems: 'flex-start',
        gap: 10,
        cursor: isDisabled ? 'not-allowed' : 'pointer',
        userSelect: 'none',
        opacity: isDisabled ? 0.6 : 1,
        ...style,
      }}
    >
      {inputElement}
      <span style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        {label && (
          <span style={{ fontSize: 14, color: 'var(--color-ink)', lineHeight: 1.25 }}>{label}</span>
        )}
        {hint && (
          <span style={{ fontSize: 12, color: 'var(--color-ink-3)', lineHeight: 1.25 }}>
            {hint}
          </span>
        )}
      </span>
    </label>
  );
});

// packages/ui-ng/src/lib/radio/radio.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  forwardRef,
  inject,
  input,
  signal,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

export type RadioGroupOrientation = 'vertical' | 'horizontal';

let radioGroupCounter = 0;

@Component({
  selector: 'flr-radio-group',
  exportAs: 'flrRadioGroup',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => RadioGroupComponent), multi: true },
  ],
  template: `
    <div
      class="flr-radio-group"
      role="radiogroup"
      [attr.aria-label]="ariaLabel()"
      [class.flr-radio-group--horizontal]="orientation() === 'horizontal'"
    >
      <ng-content />
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-radio-group {
      display: flex;
      flex-direction: column;
      gap: 10px;
    }
    .flr-radio-group--horizontal {
      flex-direction: row;
      gap: 16px;
    }
  `,
})
export class RadioGroupComponent implements ControlValueAccessor {
  readonly orientation = input<RadioGroupOrientation>('vertical');
  readonly ariaLabel = input<string | null>(null, { alias: 'aria-label' });
  readonly name = input<string>(`flr-radio-${++radioGroupCounter}`);

  readonly value = signal<string | number | null>(null);
  readonly disabled = signal(false);

  private onChange: (value: string | number) => void = () => {};
  onTouched: () => void = () => {};

  writeValue(value: string | number | null): void {
    this.value.set(value);
  }

  registerOnChange(fn: (value: string | number) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  select(value: string | number): void {
    this.value.set(value);
    this.onChange(value);
    this.onTouched();
  }
}

@Component({
  selector: 'flr-radio',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label class="flr-radio" [class.flr-radio--disabled]="isDisabled()">
      <span
        class="flr-radio__box"
        [class.flr-radio__box--invalid]="invalid()"
        [class.flr-radio__box--focused]="focused()"
      >
        <input
          type="radio"
          class="flr-radio__input"
          [attr.id]="inputId()"
          [attr.name]="groupName()"
          [value]="value()"
          [checked]="checked()"
          [disabled]="isDisabled()"
          [attr.aria-invalid]="invalid() || null"
          (change)="select()"
          (focus)="focused.set(true)"
          (blur)="handleBlur()"
        />
        <span
          class="flr-radio__dot"
          [class.flr-radio__dot--on]="checked()"
          aria-hidden="true"
        ></span>
      </span>
      @if (label() || hint()) {
        <span class="flr-radio__text">
          @if (label(); as l) {
            <span class="flr-radio__label">{{ l }}</span>
          }
          @if (hint(); as h) {
            <span class="flr-radio__hint">{{ h }}</span>
          }
        </span>
      }
    </label>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-radio {
      display: inline-flex;
      align-items: flex-start;
      gap: 10px;
      cursor: pointer;
      user-select: none;
    }
    .flr-radio--disabled {
      cursor: not-allowed;
      opacity: 0.6;
    }
    .flr-radio__box {
      position: relative;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 16px;
      height: 16px;
      flex-shrink: 0;
      border-radius: 999px;
      background: var(--color-card, #ffffff);
      border: 1px solid var(--color-rule-strong, rgba(30, 41, 59, 0.28));
      transition:
        border-color 140ms,
        box-shadow 140ms;
    }
    .flr-radio__box--invalid {
      border-color: var(--color-danger, #dc2626);
    }
    .flr-radio__box--focused {
      box-shadow: 0 0 0 3px
        color-mix(in oklab, var(--color-accent, var(--color-ink, #1e293b)) 30%, transparent);
    }
    .flr-radio__box--invalid.flr-radio__box--focused {
      box-shadow: 0 0 0 3px color-mix(in oklab, var(--color-danger, #dc2626) 30%, transparent);
    }
    .flr-radio--disabled .flr-radio__box {
      background: var(--color-paper-2, #f3efe7);
    }
    .flr-radio__input {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
      margin: 0;
      opacity: 0;
      cursor: inherit;
    }
    .flr-radio__dot {
      width: 8px;
      height: 8px;
      border-radius: 999px;
      background: var(--color-accent, var(--color-ink, #1e293b));
      opacity: 0;
      transition: opacity 120ms;
      pointer-events: none;
    }
    .flr-radio__dot--on {
      opacity: 1;
    }
    .flr-radio__text {
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .flr-radio__label {
      font-size: 14px;
      color: var(--color-ink, #1e293b);
      line-height: 1.25;
    }
    .flr-radio__hint {
      font-size: 12px;
      color: var(--color-ink-3, #64748b);
      line-height: 1.25;
    }
  `,
})
export class RadioComponent {
  private readonly group = inject(RadioGroupComponent, { optional: true });

  readonly value = input.required<string | number>();
  readonly label = input<string | null>(null);
  readonly hint = input<string | null>(null);
  readonly invalid = input(false);
  readonly disabled = input(false);
  readonly inputId = input<string | null>(null, { alias: 'id' });

  protected readonly focused = signal(false);

  protected readonly checked = computed(() => {
    const groupValue = this.group?.value();
    return groupValue != null && String(groupValue) === String(this.value());
  });

  protected readonly isDisabled = computed(
    () => this.disabled() || (this.group?.disabled() ?? false),
  );
  protected readonly groupName = computed(() => this.group?.name() ?? null);

  protected select(): void {
    this.group?.select(this.value());
  }

  protected handleBlur(): void {
    this.focused.set(false);
    this.group?.onTouched();
  }
}
