// packages/react/src/components/app/Tag.tsx
import type { ReactNode, MouseEvent as ReactMouseEvent } from 'react';

export type TagVariant = 'neutral' | 'accent' | 'success' | 'warning' | 'danger';
export type TagSize = 'sm' | 'md';

interface Props {
  children: ReactNode;
  /** Semantic variant — picks colour automatically. Mutually exclusive with `color`. */
  variant?: TagVariant;
  /** Explicit hex / CSS color override. Wins over `variant`. */
  color?: string;
  /** When true, fills the chip with a soft tint. When false, transparent + bordered. */
  soft?: boolean;
  /** Show the leading dot. Default true (the editorial look). */
  dot?: boolean;
  size?: TagSize;
  icon?: ReactNode;
  onRemove?: () => void;
  className?: string;
}

const variantColor: Record<TagVariant, string> = {
  neutral: 'var(--color-fg-2)',
  accent: 'var(--color-accent)',
  success: '#10b981',
  warning: '#f59e0b',
  danger: '#dc2626',
};

const sizeMap: Record<TagSize, { padding: string; fontSize: number; gap: number; dot: number }> = {
  sm: { padding: '2px 7px', fontSize: 9.5, gap: 5, dot: 4 },
  md: { padding: '3px 9px', fontSize: 10.5, gap: 6, dot: 5 },
};

/**
 * Editorial pill — mono uppercase label with a leading dot. Used for status,
 * type, owner, role. Pick a `variant` for semantic meaning, or pass `color`
 * for full control.
 */
export function Tag({
  children,
  variant,
  color,
  soft,
  dot = true,
  size = 'md',
  icon,
  onRemove,
  className,
}: Props) {
  const c = color ?? (variant ? variantColor[variant] : 'var(--color-fg-2)');
  const dim = sizeMap[size];

  return (
    <span
      className={['mono', className].filter(Boolean).join(' ')}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: dim.gap,
        padding: dim.padding,
        borderRadius: 999,
        fontSize: dim.fontSize,
        background: soft ? `color-mix(in oklab, ${c} 14%, transparent)` : 'transparent',
        border: soft ? 'none' : '1px solid var(--color-rule)',
        color: c,
        letterSpacing: '0.05em',
        textTransform: 'uppercase',
        whiteSpace: 'nowrap',
      }}
    >
      {dot && (
        <span
          aria-hidden
          style={{
            width: dim.dot,
            height: dim.dot,
            borderRadius: dim.dot / 2,
            background: c,
            flexShrink: 0,
          }}
        />
      )}
      {icon && <span aria-hidden>{icon}</span>}
      {children}
      {onRemove && (
        <button
          type="button"
          aria-label="Remove"
          onClick={(e: ReactMouseEvent<HTMLButtonElement>) => {
            e.stopPropagation();
            onRemove();
          }}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: dim.dot * 2.4,
            height: dim.dot * 2.4,
            border: 'none',
            background: 'transparent',
            color: 'inherit',
            cursor: 'pointer',
            padding: 0,
            opacity: 0.6,
          }}
          onMouseEnter={(e) => (e.currentTarget.style.opacity = '1')}
          onMouseLeave={(e) => (e.currentTarget.style.opacity = '0.6')}
        >
          <svg viewBox="0 0 12 12" width="8" height="8" fill="none">
            <path
              d="m3 3 6 6M3 9 9 3"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
          </svg>
        </button>
      )}
    </span>
  );
}

// packages/ui-ng/src/lib/tag/tag.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';

export type TagVariant = 'neutral' | 'accent' | 'success' | 'warning' | 'danger';
export type TagSize = 'sm' | 'md';

const VARIANT_COLOR: Record<TagVariant, string> = {
  neutral: 'var(--color-fg-2)',
  accent: 'var(--color-accent)',
  success: '#10b981',
  warning: '#f59e0b',
  danger: '#dc2626',
};

const SIZE: Record<TagSize, { padding: string; fontSize: string; gap: string; dot: number }> = {
  sm: { padding: '2px 7px', fontSize: '9.5px', gap: '5px', dot: 4 },
  md: { padding: '3px 9px', fontSize: '10.5px', gap: '6px', dot: 5 },
};

/**
 * Editorial pill — Angular 22 port of `@ferrlabs/ui-react`'s Tag. Mono
 * uppercase label with a leading dot. Pick a semantic `variant` or pass an
 * explicit `color`. `removable` shows a × button and emits `removed`. Project
 * a leading icon via the `[tag-icon]` slot.
 */
@Component({
  selector: 'flr-tag',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span class="flr-tag mono" [style]="styles()">
      @if (dot()) {
        <span class="flr-tag__dot" aria-hidden="true" [style]="dotStyles()"></span>
      }
      <ng-content select="[tag-icon]" />
      <ng-content />
      @if (removable()) {
        <button
          type="button"
          class="flr-tag__remove"
          aria-label="Remove"
          [style.width.px]="dim().dot * 2.4"
          [style.height.px]="dim().dot * 2.4"
          (click)="remove($event)"
        >
          <svg viewBox="0 0 12 12" width="8" height="8" fill="none">
            <path
              d="m3 3 6 6M3 9 9 3"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linecap="round"
            />
          </svg>
        </button>
      }
    </span>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-tag {
      display: inline-flex;
      align-items: center;
      border-radius: 999px;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      white-space: nowrap;
    }
    .flr-tag__dot {
      border-radius: 999px;
      flex-shrink: 0;
    }
    .flr-tag__remove {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: none;
      background: transparent;
      color: inherit;
      cursor: pointer;
      padding: 0;
      opacity: 0.6;
    }
    .flr-tag__remove:hover {
      opacity: 1;
    }
  `,
})
export class TagComponent {
  readonly variant = input<TagVariant | null>(null);
  readonly color = input<string | null>(null);
  readonly soft = input(false);
  readonly dot = input(true);
  readonly size = input<TagSize>('md');
  readonly removable = input(false);

  readonly removed = output<void>();

  protected readonly dim = computed(() => SIZE[this.size()]);

  protected readonly resolvedColor = computed(() => {
    const explicit = this.color();
    if (explicit) return explicit;
    const variant = this.variant();
    return variant ? VARIANT_COLOR[variant] : 'var(--color-fg-2)';
  });

  protected readonly styles = computed<Record<string, string>>(() => {
    const dim = this.dim();
    const c = this.resolvedColor();
    return {
      gap: dim.gap,
      padding: dim.padding,
      'font-size': dim.fontSize,
      background: this.soft() ? `color-mix(in oklab, ${c} 14%, transparent)` : 'transparent',
      border: this.soft() ? 'none' : '1px solid var(--color-rule)',
      color: c,
    };
  });

  protected readonly dotStyles = computed<Record<string, string>>(() => {
    const dim = this.dim();
    return { width: `${dim.dot}px`, height: `${dim.dot}px`, background: this.resolvedColor() };
  });

  protected remove(event: MouseEvent): void {
    event.stopPropagation();
    this.removed.emit();
  }
}
