// packages/ui/src/react/components/app/Shell.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { Sidebar, SidebarSection, SidebarItem } from '../../../primitives';
import { LogoMark, type ProductSlug } from './LogoMark';
import { BrandDropdown, type BrandDropdownAppId, type BrandDropdownApp } from './BrandDropdown';
import { UserMenu, type UserMenuItem } from './UserMenu';

export interface NavItem {
  id: string;
  label: string;
  icon: ReactNode;
  href: string;
  badge?: string | number | null;
}

export interface NavGroup {
  title?: string;
  items: NavItem[];
}

export interface ShellProps {
  product: ProductSlug;
  productName: string;
  marketingHref: string;
  accent: string;

  sections: NavGroup[];

  currentPath: string;
  onNavigate: (href: string) => void;

  projectName?: string;
  projectMeta?: string;
  onProjectClick?: () => void;

  breadcrumb?: ReactNode[];
  topbarRight?: ReactNode;

  appSwitcher?: { current: BrandDropdownAppId; apps?: BrandDropdownApp[] };

  /**
   * When present, the topbar renders a clickable search trigger styled as
   * a `⌘K` hint button. The handler is the consumer's responsibility — it
   * typically opens a command palette / search modal. The same handler is
   * also bound to the cmd/ctrl+K keyboard shortcut globally on the Shell.
   */
  onSearch?: () => void;

  /**
   * When present, an avatar + name button appears at the far right of the
   * topbar. Clicking opens a dropdown with the supplied items (Profile,
   * Sign out, etc.). Pass `null` to omit on auth/login surfaces.
   */
  userMenu?: {
    name: string;
    email?: string;
    avatarSrc?: string | null;
    items: UserMenuItem[];
    showName?: boolean;
  };

  children: ReactNode;
}

export function Shell({
  product,
  productName,
  marketingHref,
  accent,
  sections,
  currentPath,
  onNavigate,
  projectName,
  projectMeta,
  onProjectClick,
  breadcrumb,
  topbarRight,
  appSwitcher,
  onSearch,
  userMenu,
  children,
}: ShellProps) {
  const [collapsed, setCollapsed] = useState(false);

  useEffect(() => {
    if (!onSearch) return;
    const handler = (e: KeyboardEvent) => {
      const isK = e.key === 'k' || e.key === 'K';
      if (isK && (e.metaKey || e.ctrlKey) && !e.altKey && !e.shiftKey) {
        e.preventDefault();
        onSearch();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onSearch]);

  const isActive = (href: string) => {
    if (href === '/') return currentPath === '/';
    return currentPath === href || currentPath.startsWith(`${href}/`);
  };

  const brand = appSwitcher ? (
    <BrandDropdown current={appSwitcher.current} apps={appSwitcher.apps} collapsed={collapsed}>
      <LogoMark accent={accent} product={product} />
      {!collapsed && (
        <span style={{ display: 'flex', flexDirection: 'column', lineHeight: 1.1, minWidth: 0 }}>
          <span
            style={{
              fontFamily: 'var(--font-serif)',
              fontWeight: 900,
              fontSize: 17,
              letterSpacing: '-0.02em',
            }}
          >
            {productName.toLowerCase()}
          </span>
          <span
            className="mono"
            style={{
              fontSize: 9.5,
              color: 'var(--color-fg-3)',
              letterSpacing: '0.08em',
              marginTop: 2,
            }}
          >
            by ferrlabs
          </span>
        </span>
      )}
    </BrandDropdown>
  ) : (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        padding: collapsed ? '20px 0' : '20px 20px',
        justifyContent: collapsed ? 'center' : 'flex-start',
        width: '100%',
      }}
    >
      <LogoMark accent={accent} product={product} />
      {!collapsed && (
        <div style={{ display: 'flex', flexDirection: 'column', lineHeight: 1.1, minWidth: 0 }}>
          <span
            style={{
              fontFamily: 'var(--font-serif)',
              fontWeight: 900,
              fontSize: 17,
              letterSpacing: '-0.02em',
            }}
          >
            {productName.toLowerCase()}
          </span>
          <a
            href={marketingHref}
            className="mono"
            style={{
              fontSize: 9.5,
              color: 'var(--color-fg-3)',
              letterSpacing: '0.08em',
              marginTop: 2,
            }}
          >
            by ferrlabs ↗
          </a>
        </div>
      )}
    </div>
  );

  return (
    <div
      className="ferrlabs-app-shell"
      style={{
        display: 'grid',
        gridTemplateColumns: collapsed ? '64px 1fr' : '256px 1fr',
        minHeight: '100vh',
        transition: 'grid-template-columns 220ms ease',
      }}
    >
      <Sidebar
        brand={brand}
        project={
          projectName
            ? { name: projectName, meta: projectMeta, onClick: onProjectClick, accent }
            : undefined
        }
        collapsed={collapsed}
        onCollapsedChange={setCollapsed}
      >
        {sections.map((group, gi) => (
          <SidebarSection key={group.title ?? `g-${gi}`} title={group.title} collapsed={collapsed}>
            {group.items.map((item) => (
              <SidebarItem
                key={item.id}
                icon={item.icon}
                label={item.label}
                href={item.href}
                active={isActive(item.href)}
                collapsed={collapsed}
                accent={accent}
                badge={item.badge ?? undefined}
                onClick={() => onNavigate(item.href)}
              />
            ))}
          </SidebarSection>
        ))}
      </Sidebar>

      <div style={{ display: 'flex', flexDirection: 'column', minWidth: 0 }}>
        <header
          style={{
            height: 64,
            display: 'flex',
            alignItems: 'center',
            padding: '0 28px',
            borderBottom: '1px solid var(--color-rule)',
            background: 'var(--color-bg)',
            position: 'sticky',
            top: 0,
            zIndex: 5,
            gap: 16,
          }}
        >
          <div
            className="mono"
            style={{
              fontSize: 12,
              color: 'var(--color-fg-3)',
              display: 'flex',
              gap: 6,
              alignItems: 'center',
            }}
          >
            {(breadcrumb ?? []).map((b, i, a) => (
              <span key={i} style={{ display: 'inline-flex', gap: 6, alignItems: 'center' }}>
                <span
                  style={{ color: i === a.length - 1 ? 'var(--color-fg)' : 'var(--color-fg-3)' }}
                >
                  {b}
                </span>
                {i < a.length - 1 && <span style={{ opacity: 0.5 }}>/</span>}
              </span>
            ))}
          </div>
          <div style={{ flex: 1 }} />
          {onSearch && (
            <button
              type="button"
              onClick={onSearch}
              aria-label="Open search (Cmd+K)"
              className="mono"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                padding: '6px 10px 6px 12px',
                borderRadius: 8,
                border: '1px solid var(--color-rule)',
                background: 'var(--color-bg-2, #f4f4f2)',
                color: 'var(--color-fg-3)',
                fontSize: 12,
                cursor: 'pointer',
                transition: 'background 120ms, border-color 120ms',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = 'var(--color-card, #fff)';
                e.currentTarget.style.borderColor = 'var(--color-rule-strong)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = 'var(--color-bg-2, #f4f4f2)';
                e.currentTarget.style.borderColor = 'var(--color-rule)';
              }}
            >
              <span style={{ opacity: 0.7 }}>Search</span>
              <kbd
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  padding: '1px 5px',
                  borderRadius: 4,
                  border: '1px solid var(--color-rule)',
                  background: 'var(--color-card, #fff)',
                  fontFamily: 'inherit',
                  fontSize: 10.5,
                  letterSpacing: '0.04em',
                }}
              >
                ⌘K
              </kbd>
            </button>
          )}
          {topbarRight && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>{topbarRight}</div>
          )}
          {userMenu && (
            <UserMenu
              name={userMenu.name}
              email={userMenu.email}
              avatarSrc={userMenu.avatarSrc}
              accent={accent}
              items={userMenu.items}
              showName={userMenu.showName}
            />
          )}
        </header>
        <main style={{ flex: 1, overflowY: 'auto', background: 'var(--color-bg)' }}>
          {children}
        </main>
      </div>

      <style>{`
        @media (max-width: 880px) {
          .ferrlabs-app-shell { grid-template-columns: 1fr !important; }
          .ferrlabs-app-shell > aside { display: none; }
        }
      `}</style>
    </div>
  );
}

// packages/ui-ng/src/lib/shell/shell.component.ts
import { ChangeDetectionStrategy, Component, inject, input, model, output } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import {
  SidebarComponent,
  SidebarItemComponent,
  SidebarSectionComponent,
} from '../sidebar/sidebar.component';
import { isTrustedIconMarkup } from '../icon/icon-markup';

export interface ShellNavItem {
  readonly id: string;
  readonly label: string;
  readonly icon?: string;
  readonly href?: string;
  readonly badge?: string | number | null;
  readonly danger?: boolean;
  readonly disabled?: boolean;
}

export interface ShellNavGroup {
  readonly title?: string;
  readonly items: readonly ShellNavItem[];
}

@Component({
  selector: 'flr-shell',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SidebarComponent, SidebarSectionComponent, SidebarItemComponent],
  host: {
    '(window:keydown)': 'onKeydown($event)',
  },
  template: `
    <div class="flr-shell">
      <div class="flr-shell__rail"><ng-content select="[shell-rail]" /></div>
      <div class="flr-shell__surface">
        <flr-sidebar [(collapsed)]="collapsed">
          <div sidebar-brand class="flr-shell__brand"><ng-content select="[shell-brand]" /></div>
          <div sidebar-project><ng-content select="[shell-project]" /></div>
          @for (group of sections(); track group.title ?? $index) {
            <flr-sidebar-section [title]="group.title ?? null" [collapsed]="collapsed()">
              @for (item of group.items; track item.id) {
                <flr-sidebar-item
                  [label]="item.label"
                  [href]="item.href ?? null"
                  [active]="isActive(item)"
                  [collapsed]="collapsed()"
                  [accent]="accent()"
                  [badge]="item.badge ?? null"
                  [danger]="item.danger ?? false"
                  [disabled]="item.disabled ?? false"
                  (selected)="onSelect(item)"
                >
                  @if (item.icon) {
                    <span item-icon>
                      @let icon = trustedIcon(item.icon);
                      @if (icon) {
                        <span [innerHTML]="icon"></span>
                      } @else {
                        {{ item.icon }}
                      }
                    </span>
                  }
                </flr-sidebar-item>
              }
            </flr-sidebar-section>
          }
        </flr-sidebar>

        <div class="flr-shell__body">
          <header class="flr-shell__topbar">
            <div class="flr-shell__slot flr-shell__slot--crumb-lead">
              <ng-content select="[shell-breadcrumb-lead]" />
            </div>
            @if (breadcrumb().length) {
              <div class="mono flr-shell__crumbs">
                @for (crumb of breadcrumb(); track $index; let last = $last) {
                  <span class="flr-shell__crumb" [class.flr-shell__crumb--last]="last">{{
                    crumb
                  }}</span>
                  @if (!last) {
                    <span class="flr-shell__crumb-sep">/</span>
                  }
                }
              </div>
            }
            <div class="flr-shell__slot flr-shell__slot--crumb">
              <ng-content select="[shell-breadcrumb-actions]" />
            </div>
            <div class="flr-shell__spacer"></div>
            @if (searchEnabled()) {
              <button
                type="button"
                class="flr-shell__search mono"
                aria-label="Open search (Cmd+K)"
                (click)="search.emit()"
              >
                <span>Search</span>
                <kbd class="flr-shell__kbd">⌘K</kbd>
              </button>
            }
            <div class="flr-shell__slot"><ng-content select="[shell-actions]" /></div>
            <div class="flr-shell__slot"><ng-content select="[shell-topbar-right]" /></div>
            <div class="flr-shell__slot"><ng-content select="[shell-user]" /></div>
          </header>
          <main class="flr-shell__main" tabindex="0"><ng-content /></main>
        </div>
      </div>
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
    .flr-shell {
      display: flex;
      height: 100dvh;
      background: var(--color-app-rail, #101012);
    }
    .flr-shell__surface {
      display: flex;
      flex: 1;
      min-width: 0;
      background: var(--color-app-bg, #fafaf9);
    }
    .flr-shell:has(.flr-shell__rail:not(:empty)) .flr-shell__surface {
      --flr-sidebar-height: calc(100dvh - var(--flr-shell-inset, 10px));
      margin-top: var(--flr-shell-inset, 10px);
      border-top-left-radius: var(--flr-shell-radius, 14px);
      overflow: clip;
    }
    .flr-shell:not(:has(.flr-shell__rail:not(:empty))) {
      background: var(--color-app-bg, #fafaf9);
    }
    .flr-shell__rail {
      display: flex;
      align-self: stretch;
    }
    .flr-shell__rail:empty {
      display: none;
    }
    .flr-shell__brand {
      display: flex;
      align-items: stretch;
      width: 100%;
    }
    .flr-shell__body {
      display: flex;
      flex-direction: column;
      flex: 1;
      min-width: 0;
      min-height: 0;
    }
    .flr-shell__topbar {
      height: 64px;
      display: flex;
      align-items: center;
      padding: 0 28px;
      gap: 16px;
      border-bottom: 1px solid var(--color-rule, rgba(30, 41, 59, 0.14));
      background: var(--color-app-bg, #fafaf9);
      position: sticky;
      top: 0;
      z-index: 5;
    }
    .flr-shell__crumbs {
      font-size: 12px;
      color: var(--color-ink-3, #64748b);
      display: flex;
      gap: 6px;
      align-items: center;
    }
    .flr-shell__crumb--last {
      color: var(--color-ink, #1e293b);
    }
    .flr-shell__crumb-sep {
      opacity: 0.5;
    }
    .flr-shell__spacer {
      flex: 1;
    }
    .flr-shell__search {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 6px 10px 6px 12px;
      border-radius: 8px;
      border: 1px solid var(--color-rule, rgba(30, 41, 59, 0.14));
      background: var(--color-app-bg-2, #f4f4f2);
      color: var(--color-ink-3, #64748b);
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-size: 12px;
      cursor: pointer;
      transition:
        background 120ms,
        border-color 120ms;
    }
    .flr-shell__search:hover {
      background: var(--color-card, #fff);
      border-color: var(--color-rule-strong, rgba(30, 41, 59, 0.24));
    }
    .flr-shell__kbd {
      display: inline-flex;
      align-items: center;
      padding: 1px 5px;
      border-radius: 4px;
      border: 1px solid var(--color-rule, rgba(30, 41, 59, 0.14));
      background: var(--color-card, #fff);
      font-family: inherit;
      font-size: 10.5px;
      letter-spacing: 0.04em;
    }
    .flr-shell__slot {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .flr-shell__slot:empty {
      display: none;
    }
    .flr-shell__slot--crumb {
      margin-left: 4px;
    }
    .flr-shell__slot--crumb-lead:not(:empty) + .flr-shell__crumbs::before {
      content: '/';
      margin-right: 6px;
      color: var(--color-ink-3, #64748b);
      opacity: 0.5;
    }
    .flr-shell__main {
      flex: 1;
      min-height: 0;
      overflow-y: auto;
      background: var(--color-app-bg, #fafaf9);
    }
  `,
})
export class ShellComponent {
  readonly productName = input('');
  readonly marketingHref = input<string | null>(null);
  readonly accent = input<string | null>(null);
  readonly sections = input<readonly ShellNavGroup[]>([]);
  readonly currentPath = input('/');
  readonly breadcrumb = input<readonly string[]>([]);
  readonly searchEnabled = input(false);

  readonly collapsed = model(false);

  readonly navigate = output<string>();
  readonly search = output<void>();

  private readonly sanitizer = inject(DomSanitizer);

  protected isActive(item: ShellNavItem): boolean {
    const href = item.href;
    if (!href) return false;
    const path = this.currentPath();
    if (href === '/') return path === '/';
    return path === href || path.startsWith(`${href}/`);
  }

  protected onSelect(item: ShellNavItem): void {
    if (item.href) this.navigate.emit(item.href);
  }

  protected trustedIcon(markup: string): SafeHtml | null {
    return isTrustedIconMarkup(markup) ? this.sanitizer.bypassSecurityTrustHtml(markup) : null;
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.searchEnabled()) return;
    const isK = event.key === 'k' || event.key === 'K';
    if (isK && (event.metaKey || event.ctrlKey) && !event.altKey && !event.shiftKey) {
      event.preventDefault();
      this.search.emit();
    }
  }
}
