// packages/primitives/src/Checkbox.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type InputHTMLAttributes,
  type ReactNode,
} from 'react';

export interface CheckboxProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'type' | 'size' | 'children'
> {
  label?: ReactNode;
  hint?: ReactNode;
  invalid?: boolean;
  indeterminate?: boolean;
}

const inputStyles =
  'peer appearance-none size-4 rounded border border-slate-300 bg-white cursor-pointer transition-colors duration-150 checked:bg-accent checked:border-accent indeterminate:bg-accent indeterminate:border-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/40 disabled:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50';

const checkmark =
  'after:content-[\'\'] after:absolute after:inset-0 after:bg-no-repeat after:bg-center after:opacity-0 peer-checked:after:opacity-100 peer-indeterminate:after:opacity-100 peer-checked:after:bg-[url("data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20viewBox%3D%270%200%2016%2016%27%20fill%3D%27none%27%3E%3Cpath%20stroke%3D%27white%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%20stroke-width%3D%272%27%20d%3D%27m4%208%203%203%205-6%27/%3E%3C/svg%3E")] peer-indeterminate:after:bg-[url("data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20viewBox%3D%270%200%2016%2016%27%20fill%3D%27none%27%3E%3Cpath%20stroke%3D%27white%27%20stroke-linecap%3D%27round%27%20stroke-width%3D%272%27%20d%3D%27M4%208h8%27/%3E%3C/svg%3E")] after:pointer-events-none';

const invalidStyles = 'border-red-500 focus-visible:ring-red-500/40';

function classes(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(' ');
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  { label, hint, invalid, indeterminate, className, disabled, id, ...rest },
  ref,
) {
  const innerRef = useRef<HTMLInputElement>(null);
  useImperativeHandle(ref, () => innerRef.current as HTMLInputElement);

  useEffect(() => {
    if (innerRef.current) innerRef.current.indeterminate = Boolean(indeterminate);
  }, [indeterminate]);

  const inputElement = (
    <span className={classes('relative inline-block size-4 shrink-0', checkmark)}>
      <input
        ref={innerRef}
        id={id}
        type="checkbox"
        disabled={disabled}
        className={classes(inputStyles, invalid && invalidStyles)}
        aria-invalid={invalid || undefined}
        {...rest}
      />
    </span>
  );

  if (!label && !hint) {
    return <span className={className}>{inputElement}</span>;
  }

  return (
    <label
      className={classes(
        'inline-flex items-start gap-2.5 cursor-pointer select-none',
        disabled && 'cursor-not-allowed opacity-60',
        className,
      )}
    >
      {inputElement}
      <span className="flex flex-col gap-0.5">
        {label && <span className="text-sm text-slate-900 leading-tight">{label}</span>}
        {hint && <span className="text-xs text-slate-500 leading-tight">{hint}</span>}
      </span>
    </label>
  );
});

// packages/ui-ng/src/lib/checkbox/checkbox.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  forwardRef,
  input,
  signal,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'flr-checkbox',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => CheckboxComponent), multi: true },
  ],
  template: `
    <label class="flr-checkbox" [class.flr-checkbox--disabled]="disabled()">
      <span
        class="flr-checkbox__box"
        [class.flr-checkbox__box--on]="isOn()"
        [class.flr-checkbox__box--invalid]="invalid()"
        [class.flr-checkbox__box--focused]="focused()"
      >
        <input
          type="checkbox"
          class="flr-checkbox__input"
          [attr.id]="inputId()"
          [checked]="checked()"
          [indeterminate]="indeterminate()"
          [disabled]="disabled()"
          [attr.aria-invalid]="invalid() || null"
          (change)="toggle($event)"
          (focus)="focused.set(true)"
          (blur)="handleBlur()"
        />
        <span
          class="flr-checkbox__icon"
          [class.flr-checkbox__icon--on]="isOn()"
          [class.flr-checkbox__icon--indeterminate]="indeterminate()"
          aria-hidden="true"
        ></span>
      </span>
      @if (label() || hint()) {
        <span class="flr-checkbox__text">
          @if (label(); as l) {
            <span class="flr-checkbox__label">{{ l }}</span>
          }
          @if (hint(); as h) {
            <span class="flr-checkbox__hint">{{ h }}</span>
          }
        </span>
      }
    </label>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-checkbox {
      display: inline-flex;
      align-items: flex-start;
      gap: 10px;
      cursor: pointer;
      user-select: none;
    }
    .flr-checkbox--disabled {
      cursor: not-allowed;
      opacity: 0.6;
    }
    .flr-checkbox__box {
      position: relative;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 16px;
      height: 16px;
      flex-shrink: 0;
      border-radius: 4px;
      background: var(--color-card, #ffffff);
      border: 1px solid var(--color-rule-strong, rgba(30, 41, 59, 0.28));
      transition:
        background 140ms,
        border-color 140ms,
        box-shadow 140ms;
    }
    .flr-checkbox__box--on {
      background: var(--color-accent, var(--color-ink, #1e293b));
      border-color: var(--color-accent, var(--color-ink, #1e293b));
    }
    .flr-checkbox__box--invalid {
      border-color: var(--color-danger, #dc2626);
    }
    .flr-checkbox__box--focused {
      box-shadow: 0 0 0 3px
        color-mix(in oklab, var(--color-accent, var(--color-ink, #1e293b)) 30%, transparent);
    }
    .flr-checkbox__box--invalid.flr-checkbox__box--focused {
      box-shadow: 0 0 0 3px color-mix(in oklab, var(--color-danger, #dc2626) 30%, transparent);
    }
    .flr-checkbox--disabled .flr-checkbox__box {
      background: var(--color-paper-2, #f3efe7);
    }
    .flr-checkbox__input {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
      margin: 0;
      opacity: 0;
      cursor: inherit;
    }
    .flr-checkbox__icon {
      position: absolute;
      inset: 0;
      pointer-events: none;
      background-repeat: no-repeat;
      background-position: center;
      background-size: 12px 12px;
      opacity: 0;
      transition: opacity 120ms;
    }
    .flr-checkbox__icon--on {
      opacity: 1;
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none'%3E%3Cpath stroke='white' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m4 8 3 3 5-6'/%3E%3C/svg%3E");
    }
    .flr-checkbox__icon--indeterminate {
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none'%3E%3Cpath stroke='white' stroke-linecap='round' stroke-width='2' d='M4 8h8'/%3E%3C/svg%3E");
    }
    .flr-checkbox__text {
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .flr-checkbox__label {
      font-size: 14px;
      color: var(--color-ink, #1e293b);
      line-height: 1.25;
    }
    .flr-checkbox__hint {
      font-size: 12px;
      color: var(--color-ink-3, #64748b);
      line-height: 1.25;
    }
  `,
})
export class CheckboxComponent implements ControlValueAccessor {
  readonly label = input<string | null>(null);
  readonly hint = input<string | null>(null);
  readonly invalid = input(false);
  readonly indeterminate = input(false);
  readonly inputId = input<string | null>(null, { alias: 'id' });

  protected readonly checked = signal(false);
  protected readonly disabled = signal(false);
  protected readonly focused = signal(false);
  protected readonly isOn = computed(() => this.checked() || this.indeterminate());

  private onChange: (value: boolean) => void = () => {};
  protected onTouched: () => void = () => {};

  writeValue(value: boolean | null): void {
    this.checked.set(!!value);
  }

  registerOnChange(fn: (value: boolean) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  protected toggle(event: Event): void {
    const value = (event.target as HTMLInputElement).checked;
    this.checked.set(value);
    this.onChange(value);
  }

  protected handleBlur(): void {
    this.focused.set(false);
    this.onTouched();
  }
}
