// packages/react/src/components/app/BrandDropdown.tsx
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { LogoMark, type ProductSlug } from './LogoMark';

export type BrandDropdownAppId =
  | 'ferrflow'
  | 'ferrvault'
  | 'ferrtrack'
  | 'ferrgrowth'
  | 'ferrfleet'
  | 'ferrlabs';

export interface BrandDropdownApp {
  id: BrandDropdownAppId;
  label: string;
  tag: string;
  href: string;
  accent: string;
}

export interface BrandDropdownProps {
  current: BrandDropdownAppId;
  apps?: BrandDropdownApp[];
  children: ReactNode;
  className?: string;
  collapsed?: boolean;
}

export const DEFAULT_APPS: BrandDropdownApp[] = [
  {
    id: 'ferrlabs',
    label: 'FerrLabs',
    tag: 'Org & holding',
    href: 'https://app.ferrlabs.com',
    accent: '#1e293b',
  },
  {
    id: 'ferrgrowth',
    label: 'FerrGrowth',
    tag: 'Growth tooling',
    href: 'https://app.ferrgrowth.com',
    accent: '#7c3aed',
  },
  {
    id: 'ferrfleet',
    label: 'FerrFleet',
    tag: 'Agent fleet runtime',
    href: 'https://app.ferrfleet.com',
    accent: '#f59e0b',
  },
  {
    id: 'ferrtrack',
    label: 'FerrTrack',
    tag: 'Issue tracker',
    href: 'https://app.ferrtrack.com',
    accent: '#6366f1',
  },
  {
    id: 'ferrvault',
    label: 'FerrVault',
    tag: 'Secrets management',
    href: 'https://app.ferrvault.com',
    accent: '#10b981',
  },
];

/**
 * Clickable brand area that opens a dropdown to switch between FerrLabs apps.
 * Wraps arbitrary brand content (logo + name + tagline). The whole wrapped
 * region becomes the trigger; a chevron is appended on the right.
 */
export function BrandDropdown({
  current,
  apps = DEFAULT_APPS,
  children,
  className,
  collapsed = false,
}: BrandDropdownProps) {
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!open) return;
    const onClick = (e: MouseEvent) => {
      if (!rootRef.current?.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    document.addEventListener('mousedown', onClick);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onClick);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  const currentApp = apps.find((a) => a.id === current);

  return (
    <div
      ref={rootRef}
      className={className}
      style={{
        position: 'relative',
        display: 'flex',
        flex: 1,
        minWidth: 0,
        alignSelf: 'stretch',
        height: '100%',
      }}
    >
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-haspopup="menu"
        aria-expanded={open}
        title={currentApp ? `${currentApp.label} · switch to another FerrLabs app` : 'Switch app'}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          justifyContent: 'flex-start',
          width: '100%',
          height: '100%',
          minHeight: 'inherit',
          background: 'transparent',
          border: 'none',
          padding: '0 20px',
          margin: 0,
          cursor: 'pointer',
          color: 'inherit',
          font: 'inherit',
          textAlign: 'left',
          borderRadius: 0,
          transition: 'background 140ms ease',
          boxSizing: 'border-box',
          overflow: 'hidden',
        }}
        onMouseEnter={(e) =>
          (e.currentTarget.style.background = 'var(--color-app-nav-hover, rgba(30,41,59,0.03))')
        }
        onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
      >
        <span
          style={{
            flex: 1,
            minWidth: 0,
            display: 'inline-flex',
            alignItems: 'center',
            gap: 12,
          }}
        >
          {children}
        </span>
        <span
          aria-hidden
          style={{
            color: 'var(--color-fg-3, #64748b)',
            fontSize: 12,
            flexShrink: 0,
            opacity: collapsed ? 0 : 0.7,
            maxWidth: collapsed ? 0 : 16,
            overflow: 'hidden',
            transition: 'opacity 160ms ease, max-width 220ms ease',
          }}
        >
          ▾
        </span>
      </button>

      {open && (
        <div
          role="menu"
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            right: 0,
            background: 'var(--color-app-sidebar, #f7f7f5)',
            borderBottom: '1px solid var(--color-rule, rgba(30,41,59,0.10))',
            padding: '8px 8px 12px',
            zIndex: 60,
          }}
        >
          {!collapsed && (
            <div
              className="mono"
              style={{
                padding: '4px 12px 6px',
                fontSize: 10,
                letterSpacing: '0.14em',
                textTransform: 'uppercase',
                color: 'var(--color-fg-3, #64748b)',
              }}
            >
              Switch app
            </div>
          )}
          {apps.map((a) => {
            const isCurrent = a.id === current;
            return (
              <a
                key={a.id}
                href={a.href}
                role="menuitem"
                aria-current={isCurrent ? 'page' : undefined}
                title={collapsed ? `${a.label} — ${a.tag}` : undefined}
                style={{
                  position: 'relative',
                  display: 'flex',
                  alignItems: 'center',
                  gap: collapsed ? 0 : 12,
                  justifyContent: collapsed ? 'center' : 'flex-start',
                  padding: collapsed ? '6px 0' : '6px 12px',
                  margin: '1px 0',
                  borderRadius: 8,
                  textDecoration: 'none',
                  color: isCurrent ? 'var(--color-fg, #1e293b)' : 'var(--color-fg-2, #475569)',
                  background: isCurrent
                    ? 'var(--color-app-nav-active, rgba(30,41,59,0.06))'
                    : 'transparent',
                  fontFamily: 'var(--font-serif)',
                  fontSize: 13.5,
                  transition: 'background 120ms',
                }}
                onMouseEnter={(e) => {
                  if (!isCurrent)
                    e.currentTarget.style.background =
                      'var(--color-app-nav-hover, rgba(30,41,59,0.03))';
                }}
                onMouseLeave={(e) => {
                  if (!isCurrent) e.currentTarget.style.background = 'transparent';
                }}
              >
                {isCurrent && !collapsed && (
                  <span
                    aria-hidden
                    style={{
                      position: 'absolute',
                      left: 0,
                      top: 8,
                      bottom: 8,
                      width: 2,
                      background: a.accent,
                      borderRadius: 2,
                    }}
                  />
                )}
                <span
                  style={{
                    width: 36,
                    height: 36,
                    display: 'inline-flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: 0,
                  }}
                >
                  <LogoMark product={a.id as ProductSlug} accent={a.accent} size={36} />
                </span>
                {!collapsed && (
                  <>
                    <span
                      style={{
                        flex: 1,
                        minWidth: 0,
                        textAlign: 'left',
                        fontWeight: 700,
                      }}
                    >
                      {a.label}
                    </span>
                    <span
                      className="mono"
                      style={{
                        fontSize: 10,
                        color: 'var(--color-fg-3, #64748b)',
                        letterSpacing: '0.04em',
                        whiteSpace: 'nowrap',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        maxWidth: 110,
                      }}
                    >
                      {a.tag}
                    </span>
                  </>
                )}
              </a>
            );
          })}
        </div>
      )}
    </div>
  );
}

// packages/ui-ng/src/lib/brand-dropdown/brand-dropdown.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  signal,
} from '@angular/core';
import { LogoMarkComponent, type ProductSlug } from '../logo-mark/logo-mark.component';

export type BrandDropdownAppId =
  | 'ferrflow'
  | 'ferrvault'
  | 'ferrtrack'
  | 'ferrgrowth'
  | 'ferrfleet'
  | 'ferrlens'
  | 'ferrlabs';

export interface BrandDropdownApp {
  readonly id: BrandDropdownAppId;
  readonly label: string;
  readonly href: string;
  readonly accent: string;
  /** Visual grouping — a divider + uppercase header renders between groups. */
  readonly section?: string;
}

export const DEFAULT_APPS: readonly BrandDropdownApp[] = [
  { id: 'ferrlabs', label: 'FerrLabs', href: 'https://app.ferrlabs.com', accent: '#1e293b' },
  { id: 'ferrgrowth', label: 'FerrGrowth', href: 'https://app.ferrgrowth.com', accent: '#7c3aed' },
  { id: 'ferrfleet', label: 'FerrFleet', href: 'https://app.ferrfleet.com', accent: '#f59e0b' },
  { id: 'ferrtrack', label: 'FerrTrack', href: 'https://app.ferrtrack.com', accent: '#6366f1' },
  { id: 'ferrvault', label: 'FerrVault', href: 'https://app.ferrvault.com', accent: '#10b981' },
];

const SWITCH_OVERLAY_DELAY_MS = 200;

interface BrandRow {
  readonly app: BrandDropdownApp;
  readonly showHeader: boolean;
  readonly first: boolean;
}

@Component({
  selector: 'flr-brand-dropdown',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LogoMarkComponent],
  host: {
    '(document:mousedown)': 'onDocumentDown($event)',
    '(document:keydown.escape)': 'open.set(false)',
  },
  template: `
    <button
      type="button"
      class="flr-bd__trigger"
      [attr.aria-haspopup]="'menu'"
      [attr.aria-expanded]="open()"
      [title]="triggerTitle()"
      (click)="open.set(!open())"
    >
      <span class="flr-bd__brand"><ng-content /></span>
      <span class="flr-bd__chev" [class.flr-bd__chev--hidden]="collapsed()" aria-hidden="true"
        >▾</span
      >
    </button>

    @if (open()) {
      <div class="flr-bd__panel" role="menu">
        @if (!collapsed()) {
          <div class="mono flr-bd__eyebrow">Switch app</div>
        }
        @for (row of rows(); track row.app.id) {
          @if (row.showHeader) {
            <div class="mono flr-bd__section" [class.flr-bd__section--first]="row.first">
              {{ row.app.section }}
            </div>
          }
          <a
            class="flr-bd__app"
            [class.flr-bd__app--current]="row.app.id === current()"
            [class.flr-bd__app--collapsed]="collapsed()"
            [href]="row.app.href"
            role="menuitem"
            [attr.aria-current]="row.app.id === current() ? 'page' : null"
            [title]="collapsed() ? row.app.label : null"
            (click)="onSelect($event, row.app)"
          >
            @if (row.app.id === current() && !collapsed()) {
              <span
                class="flr-bd__bar"
                aria-hidden="true"
                [style.background]="row.app.accent"
              ></span>
            }
            <span class="flr-bd__mark">
              <flr-logo-mark [product]="$any(row.app.id)" [accent]="row.app.accent" [size]="36" />
            </span>
            @if (!collapsed()) {
              <span class="flr-bd__label">{{ row.app.label }}</span>
            }
          </a>
        }
      </div>
    }

    @if (switchVisible(); as app) {
      <div
        class="flr-bd__switch"
        aria-live="polite"
        [attr.aria-label]="'Switching to ' + app.label"
      >
        <div class="flr-bd__switch-inner">
          <span class="flr-bd__switch-mark"
            ><flr-logo-mark [product]="$any(app.id)" [accent]="app.accent" [size]="64"
          /></span>
          <span class="mono flr-bd__switch-label">Opening {{ app.label }}…</span>
        </div>
      </div>
    }
  `,
  styles: `
    :host {
      position: relative;
      display: flex;
      flex: 1;
      min-width: 0;
      align-self: stretch;
      height: 100%;
    }
    .flr-bd__trigger {
      display: flex;
      align-items: center;
      gap: 12px;
      justify-content: flex-start;
      width: 100%;
      height: 100%;
      min-height: inherit;
      background: transparent;
      border: none;
      padding: 0 18px;
      margin: 0;
      cursor: pointer;
      color: inherit;
      font: inherit;
      text-align: left;
      box-sizing: border-box;
      overflow: hidden;
      transition: background 140ms ease;
    }
    .flr-bd__trigger:hover {
      background: var(--color-app-nav-hover, rgba(30, 41, 59, 0.03));
    }
    .flr-bd__brand {
      flex: 1;
      min-width: 0;
      display: inline-flex;
      align-items: center;
      gap: 12px;
    }
    .flr-bd__chev {
      color: var(--color-ink-3, #64748b);
      font-size: 12px;
      flex-shrink: 0;
      opacity: 0.7;
      max-width: 16px;
      overflow: hidden;
      transition:
        opacity 160ms ease,
        max-width 220ms ease;
    }
    .flr-bd__chev--hidden {
      opacity: 0;
      max-width: 0;
    }
    .flr-bd__panel {
      position: absolute;
      top: 100%;
      left: 0;
      right: 0;
      height: calc(100vh - 64px - 56px);
      background: var(--color-app-sidebar, #f7f7f5);
      border-bottom: 1px solid var(--color-rule, rgba(30, 41, 59, 0.1));
      padding: 8px 8px 12px;
      z-index: 60;
      overflow-y: auto;
      animation: flr-bd-panel-in 200ms ease-out;
    }
    @keyframes flr-bd-panel-in {
      from {
        opacity: 0;
        transform: translateY(-4px);
      }
      to {
        opacity: 1;
        transform: none;
      }
    }
    .flr-bd__eyebrow {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      padding: 4px 12px 6px;
      font-size: 10px;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--color-ink-3, #64748b);
    }
    .flr-bd__section {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      padding: 10px 12px 4px;
      margin-top: 4px;
      border-top: 1px solid var(--color-rule, rgba(30, 41, 59, 0.1));
      font-size: 10px;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--color-ink-3, #64748b);
    }
    .flr-bd__section--first {
      margin-top: 0;
      border-top: none;
    }
    .flr-bd__app {
      position: relative;
      display: flex;
      align-items: center;
      gap: 12px;
      justify-content: flex-start;
      padding: 6px 12px;
      margin: 1px 0;
      border-radius: 8px;
      text-decoration: none;
      color: var(--color-ink-2, #475569);
      background: transparent;
      font-family: var(--font-display, 'Fraunces', Georgia, ui-serif, serif);
      font-size: 13.5px;
      transition: background 120ms;
    }
    .flr-bd__app:hover {
      background: var(--color-app-nav-hover, rgba(30, 41, 59, 0.03));
    }
    .flr-bd__app--current {
      color: var(--color-ink, #1e293b);
      background: var(--color-app-nav-active, rgba(30, 41, 59, 0.06));
    }
    .flr-bd__app--collapsed {
      gap: 0;
      justify-content: center;
      padding: 6px 0;
    }
    .flr-bd__bar {
      position: absolute;
      left: 0;
      top: 8px;
      bottom: 8px;
      width: 2px;
      border-radius: 2px;
    }
    .flr-bd__mark {
      width: 36px;
      height: 36px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }
    .flr-bd__label {
      flex: 1;
      min-width: 0;
      text-align: left;
      font-weight: 700;
    }
    .flr-bd__switch {
      position: fixed;
      inset: 0;
      background: var(--color-paper, #faf8f4);
      backdrop-filter: blur(10px) saturate(140%);
      -webkit-backdrop-filter: blur(10px) saturate(140%);
      z-index: 2147483600;
      display: flex;
      align-items: center;
      justify-content: center;
      animation: flr-bd-switch-in 200ms ease-out;
    }
    @keyframes flr-bd-switch-in {
      from {
        opacity: 0;
      }
      to {
        opacity: 1;
      }
    }
    @keyframes flr-bd-switch-pulse {
      0%,
      100% {
        transform: scale(1);
      }
      50% {
        transform: scale(1.06);
      }
    }
    .flr-bd__switch-inner {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 18px;
      animation: flr-bd-switch-pulse 1200ms ease-in-out infinite;
    }
    .flr-bd__switch-mark {
      width: 64px;
      height: 64px;
      border-radius: 14px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
    }
    .flr-bd__switch-label {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-size: 11px;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--color-ink-3, #64748b);
    }
  `,
})
export class BrandDropdownComponent {
  private readonly host = inject(ElementRef<HTMLElement>);

  readonly current = input.required<BrandDropdownAppId>();
  readonly apps = input<readonly BrandDropdownApp[]>(DEFAULT_APPS);
  readonly collapsed = input(false);

  protected readonly open = signal(false);
  protected readonly switchVisible = signal<BrandDropdownApp | null>(null);

  protected readonly rows = computed<BrandRow[]>(() => {
    const apps = this.apps();
    const collapsed = this.collapsed();
    return apps.map((app, i) => {
      const prevSection = i > 0 ? apps[i - 1].section : undefined;
      return {
        app,
        first: i === 0,
        showHeader: !collapsed && app.section !== undefined && app.section !== prevSection,
      };
    });
  });

  protected readonly triggerTitle = computed(() => {
    const cur = this.apps().find((a) => a.id === this.current());
    return cur ? `${cur.label} · switch to another FerrLabs app` : 'Switch app';
  });

  protected onDocumentDown(event: MouseEvent): void {
    if (!this.open()) return;
    if (!this.host.nativeElement.contains(event.target as Node)) this.open.set(false);
  }

  protected onSelect(event: MouseEvent, app: BrandDropdownApp): void {
    event.preventDefault();
    this.open.set(false);
    if (app.id === this.current()) return;
    if (typeof window === 'undefined') return;
    window.setTimeout(() => this.switchVisible.set(app), SWITCH_OVERLAY_DELAY_MS);
    window.location.assign(app.href);
  }
}
