// packages/ui/src/react/components/app/PageHeader.tsx
import { Fragment, type ReactNode } from 'react';

export interface BreadcrumbCrumb {
  label: ReactNode;
  href?: string;
}

interface Props {
  /** Mono uppercase label above the title. Free-form ReactNode. */
  eyebrow?: ReactNode;
  /** Optional breadcrumbs row above the eyebrow / title. */
  breadcrumbs?: BreadcrumbCrumb[];
  /** Fraunces 900 title. */
  title: ReactNode;
  /** Sub-headline below the title. */
  sub?: ReactNode;
  /** Inline node next to the title — typically a Tag for status / version. */
  badge?: ReactNode;
  /** Right-aligned action slot — typically Button(s). */
  actions?: ReactNode;
}

/** Per-page top chrome — Fraunces 900 title + mono eyebrow + sub + actions + optional breadcrumbs + badge. */
export function PageHeader({ eyebrow, breadcrumbs, title, sub, badge, actions }: Props) {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'flex-end',
        gap: 24,
        padding: '32px 32px 24px',
        borderBottom: '1px solid var(--color-rule)',
        flexWrap: 'wrap',
      }}
    >
      <div style={{ flex: 1, minWidth: 240 }}>
        {breadcrumbs && breadcrumbs.length > 0 && (
          <nav
            aria-label="Breadcrumb"
            className="mono"
            style={{
              fontSize: 11,
              letterSpacing: '0.06em',
              color: 'var(--color-fg-3)',
              marginBottom: eyebrow ? 8 : 12,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              flexWrap: 'wrap',
            }}
          >
            {breadcrumbs.map((c, i) => (
              <Fragment key={i}>
                {i > 0 && (
                  <span aria-hidden style={{ opacity: 0.5 }}>
                    /
                  </span>
                )}
                {c.href ? (
                  <a
                    href={c.href}
                    style={{ color: 'inherit', textDecoration: 'none' }}
                    onMouseEnter={(e) => (e.currentTarget.style.color = 'var(--color-fg)')}
                    onMouseLeave={(e) => (e.currentTarget.style.color = 'inherit')}
                  >
                    {c.label}
                  </a>
                ) : (
                  <span aria-current="page" style={{ color: 'var(--color-fg-2)' }}>
                    {c.label}
                  </span>
                )}
              </Fragment>
            ))}
          </nav>
        )}
        {eyebrow && (
          <div
            className="mono"
            style={{
              fontSize: 11,
              letterSpacing: '0.14em',
              textTransform: 'uppercase',
              color: 'var(--color-fg-3)',
              marginBottom: 12,
            }}
          >
            {eyebrow}
          </div>
        )}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <h1
            style={{
              fontFamily: 'var(--font-serif)',
              fontWeight: 900,
              fontSize: 'clamp(28px, 3vw, 40px)',
              lineHeight: 1.05,
              letterSpacing: '-0.025em',
              margin: 0,
            }}
          >
            {title}
          </h1>
          {badge}
        </div>
        {sub && (
          <p
            style={{
              fontSize: 15,
              color: 'var(--color-fg-2)',
              marginTop: 8,
              marginBottom: 0,
              maxWidth: 600,
            }}
          >
            {sub}
          </p>
        )}
      </div>
      {actions && <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>{actions}</div>}
    </div>
  );
}

// packages/ui-ng/src/lib/page-header/page-header.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

export interface BreadcrumbCrumb {
  readonly label: string;
  readonly href?: string;
}

@Component({
  selector: 'flr-page-header',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flr-ph">
      <div class="flr-ph__main">
        @if (breadcrumbs().length) {
          <nav
            class="mono flr-ph__crumbs"
            [class.flr-ph__crumbs--tight]="!!eyebrow()"
            aria-label="Breadcrumb"
          >
            @for (crumb of breadcrumbs(); track $index; let i = $index; let last = $last) {
              @if (i > 0) {
                <span class="flr-ph__crumb-sep" aria-hidden="true">/</span>
              }
              @if (crumb.href) {
                <a class="flr-ph__crumb-link" [href]="crumb.href">{{ crumb.label }}</a>
              } @else {
                <span class="flr-ph__crumb-current" aria-current="page">{{ crumb.label }}</span>
              }
            }
          </nav>
        }
        @if (eyebrow()) {
          <div class="mono flr-ph__eyebrow">{{ eyebrow() }}</div>
        }
        <div class="flr-ph__title-row">
          <h1 class="flr-ph__title">{{ title() }}</h1>
          <ng-content select="[page-header-badge]" />
        </div>
        @if (sub()) {
          <p class="flr-ph__sub">{{ sub() }}</p>
        }
      </div>
      <div class="flr-ph__actions"><ng-content select="[page-header-actions]" /></div>
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
    .flr-ph {
      display: flex;
      align-items: flex-end;
      gap: 24px;
      padding: 32px 32px 24px;
      border-bottom: 1px solid var(--color-rule, rgba(30, 41, 59, 0.14));
      flex-wrap: wrap;
    }
    .flr-ph__main {
      flex: 1;
      min-width: 240px;
    }
    .flr-ph__crumbs {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-size: 11px;
      letter-spacing: 0.06em;
      color: var(--color-ink-3, #64748b);
      margin-bottom: 12px;
      display: flex;
      align-items: center;
      gap: 6px;
      flex-wrap: wrap;
    }
    .flr-ph__crumbs--tight {
      margin-bottom: 8px;
    }
    .flr-ph__crumb-sep {
      opacity: 0.5;
    }
    .flr-ph__crumb-link {
      color: inherit;
      text-decoration: none;
    }
    .flr-ph__crumb-link:hover {
      color: var(--color-ink, #1e293b);
    }
    .flr-ph__crumb-current {
      color: var(--color-ink-2, #475569);
    }
    .flr-ph__eyebrow {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-size: 11px;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--color-ink-3, #64748b);
      margin-bottom: 12px;
    }
    .flr-ph__title-row {
      display: flex;
      align-items: center;
      gap: 12px;
      flex-wrap: wrap;
    }
    .flr-ph__title {
      font-family: var(--font-display, 'Fraunces', Georgia, ui-serif, serif);
      font-weight: 900;
      font-size: clamp(28px, 3vw, 40px);
      line-height: 1.05;
      letter-spacing: -0.025em;
      margin: 0;
    }
    .flr-ph__sub {
      font-size: 15px;
      color: var(--color-ink-2, #475569);
      margin-top: 8px;
      margin-bottom: 0;
      max-width: 600px;
    }
    .flr-ph__actions {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
    }
    .flr-ph__actions:empty {
      display: none;
    }
  `,
})
export class PageHeaderComponent {
  readonly title = input.required<string>();
  readonly eyebrow = input<string | null>(null);
  readonly sub = input<string | null>(null);
  readonly breadcrumbs = input<readonly BreadcrumbCrumb[]>([]);
}
