// packages/ui/src/primitives/Divider.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react';

export interface DividerProps extends HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical';
  label?: ReactNode;
}

export function Divider({
  orientation = 'horizontal',
  label,
  className,
  style,
  ...rest
}: DividerProps) {
  if (orientation === 'vertical') {
    return (
      <div
        role="separator"
        aria-orientation="vertical"
        className={className}
        style={{
          display: 'inline-block',
          width: 1,
          alignSelf: 'stretch',
          background: 'var(--color-rule, rgba(30, 41, 59, 0.14))',
          ...style,
        }}
        {...rest}
      />
    );
  }

  if (label) {
    const lineStyle: CSSProperties = {
      flex: 1,
      height: 1,
      background: 'var(--color-rule, rgba(30, 41, 59, 0.14))',
    };
    return (
      <div
        role="separator"
        aria-orientation="horizontal"
        className={className}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          ...style,
        }}
        {...rest}
      >
        <span style={lineStyle} />
        <span
          style={{
            fontFamily: 'var(--font-mono, "DM Mono", ui-monospace, monospace)',
            fontSize: 11,
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            color: 'var(--color-ink-3, #64748b)',
          }}
        >
          {label}
        </span>
        <span style={lineStyle} />
      </div>
    );
  }

  return (
    <hr
      role="separator"
      aria-orientation="horizontal"
      className={className}
      style={{
        border: 0,
        height: 1,
        background: 'var(--color-rule, rgba(30, 41, 59, 0.14))',
        margin: 0,
        ...style,
      }}
      {...(rest as React.HTMLAttributes<HTMLHRElement>)}
    />
  );
}

// packages/ui-ng/src/lib/divider/divider.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

export type DividerOrientation = 'horizontal' | 'vertical';

@Component({
  selector: 'flr-divider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (orientation() === 'vertical') {
      <div class="flr-divider flr-divider--v" role="separator" aria-orientation="vertical"></div>
    } @else if (label(); as text) {
      <div class="flr-divider flr-divider--labelled" role="separator" aria-orientation="horizontal">
        <span class="flr-divider__line"></span>
        <span class="flr-divider__label">{{ text }}</span>
        <span class="flr-divider__line"></span>
      </div>
    } @else {
      <hr class="flr-divider flr-divider--h" role="separator" aria-orientation="horizontal" />
    }
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-divider--v {
      display: inline-block;
      width: 1px;
      align-self: stretch;
      background: var(--color-rule, rgba(30, 41, 59, 0.14));
    }
    .flr-divider--h {
      border: 0;
      height: 1px;
      background: var(--color-rule, rgba(30, 41, 59, 0.14));
      margin: 0;
    }
    .flr-divider--labelled {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .flr-divider__line {
      flex: 1;
      height: 1px;
      background: var(--color-rule, rgba(30, 41, 59, 0.14));
    }
    .flr-divider__label {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-size: 11px;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--color-ink-3, #64748b);
    }
  `,
})
export class DividerComponent {
  readonly orientation = input<DividerOrientation>('horizontal');
  readonly label = input<string | null>(null);
}
