// packages/ui-ng/src/lib/divider/divider.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

export type DividerOrientation = 'horizontal' | 'vertical';

@Component({
  selector: 'flr-divider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (orientation() === 'vertical') {
      <div class="flr-divider flr-divider--v" role="separator" aria-orientation="vertical"></div>
    } @else if (label(); as text) {
      <div class="flr-divider flr-divider--labelled" role="separator" aria-orientation="horizontal">
        <span class="flr-divider__line"></span>
        <span class="flr-divider__label">{{ text }}</span>
        <span class="flr-divider__line"></span>
      </div>
    } @else {
      <hr class="flr-divider flr-divider--h" role="separator" aria-orientation="horizontal" />
    }
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-divider--v {
      display: inline-block;
      width: 1px;
      align-self: stretch;
      background: var(--color-rule, rgba(30, 41, 59, 0.14));
    }
    .flr-divider--h {
      border: 0;
      height: 1px;
      background: var(--color-rule, rgba(30, 41, 59, 0.14));
      margin: 0;
    }
    .flr-divider--labelled {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .flr-divider__line {
      flex: 1;
      height: 1px;
      background: var(--color-rule, rgba(30, 41, 59, 0.14));
    }
    .flr-divider__label {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-size: 11px;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--color-ink-3, #64748b);
    }
  `,
})
export class DividerComponent {
  readonly orientation = input<DividerOrientation>('horizontal');
  readonly label = input<string | null>(null);
}

// packages/primitives/src/Divider.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface DividerProps extends HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical';
  label?: ReactNode;
}

function classes(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(' ');
}

export function Divider({ orientation = 'horizontal', label, className, ...rest }: DividerProps) {
  if (orientation === 'vertical') {
    return (
      <div
        role="separator"
        aria-orientation="vertical"
        className={classes('inline-block w-px self-stretch bg-slate-200', className)}
        {...rest}
      />
    );
  }

  if (label) {
    return (
      <div
        role="separator"
        aria-orientation="horizontal"
        className={classes('flex items-center gap-3', className)}
        {...rest}
      >
        <span className="flex-1 h-px bg-slate-200" />
        <span className="text-xs text-slate-500 font-mono uppercase tracking-wider">{label}</span>
        <span className="flex-1 h-px bg-slate-200" />
      </div>
    );
  }

  return (
    <hr
      role="separator"
      aria-orientation="horizontal"
      className={classes('border-0 h-px bg-slate-200 my-0', className)}
      {...rest}
    />
  );
}
