// packages/ui-ng/src/lib/progress-bar/progress-bar.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export type ProgressBarSize = 'sm' | 'md' | 'lg';
export type ProgressBarVariant = 'accent' | 'success' | 'warning' | 'danger';

const HEIGHT: Record<ProgressBarSize, string> = {
  sm: '4px',
  md: '8px',
  lg: '12px',
};

const FILL: Record<ProgressBarVariant, string> = {
  accent: 'var(--color-accent, var(--accent, var(--color-ferrlabs-slate, #1e293b)))',
  success: 'var(--color-success, #10b981)',
  warning: 'var(--color-warning, #f59e0b)',
  danger: 'var(--color-danger, #dc2626)',
};

@Component({
  selector: 'flr-progress-bar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flr-progress">
      @if (label() || displayValue()) {
        <div class="flr-progress__meta">
          <span>{{ label() }}</span>
          @if (displayValue(); as d) {
            <span class="flr-progress__value">{{ d }}</span>
          }
        </div>
      }
      <div
        class="flr-progress__track"
        [attr.role]="label() ? 'progressbar' : null"
        [attr.aria-hidden]="label() ? null : 'true'"
        [attr.aria-valuenow]="!label() || indeterminate() ? null : value()"
        [attr.aria-valuemin]="label() ? 0 : null"
        [attr.aria-valuemax]="label() ? max() : null"
        [attr.aria-label]="label() || null"
        [style.height]="height()"
      >
        <div
          class="flr-progress__fill"
          [class.flr-progress__fill--indeterminate]="indeterminate()"
          [style.background]="fill()"
          [style.width]="indeterminate() ? '40%' : pct() + '%'"
        ></div>
      </div>
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-progress {
      display: flex;
      flex-direction: column;
      gap: 6px;
    }
    .flr-progress__meta {
      display: flex;
      align-items: center;
      justify-content: space-between;
      font-size: 12px;
      color: var(--color-ink-2, #475569);
    }
    .flr-progress__value {
      font-family: var(
        --font-mono,
        'DM Mono',
        ui-monospace,
        SFMono-Regular,
        Menlo,
        Consolas,
        monospace
      );
      color: var(--color-ink-3, #64748b);
    }
    .flr-progress__track {
      width: 100%;
      background: var(--color-rule, rgba(30, 41, 59, 0.14));
      border-radius: 999px;
      overflow: hidden;
    }
    .flr-progress__fill {
      height: 100%;
      border-radius: 999px;
      transition: width 300ms ease-out;
    }
    .flr-progress__fill--indeterminate {
      transition: none;
      animation: flr-progress-indeterminate 1.4s ease-in-out infinite;
    }
    @keyframes flr-progress-indeterminate {
      0% {
        transform: translateX(-100%);
      }
      100% {
        transform: translateX(250%);
      }
    }
  `,
})
export class ProgressBarComponent {
  readonly value = input(0);
  readonly max = input(100);
  readonly label = input<string | null>(null);
  readonly showValue = input(false);
  readonly size = input<ProgressBarSize>('md');
  readonly variant = input<ProgressBarVariant>('accent');
  readonly indeterminate = input(false);

  protected readonly pct = computed(() =>
    Math.max(0, Math.min(100, (this.value() / this.max()) * 100)),
  );
  protected readonly displayValue = computed(() =>
    this.showValue() ? `${Math.round(this.pct())}%` : null,
  );
  protected readonly height = computed(() => HEIGHT[this.size()]);
  protected readonly fill = computed(() => FILL[this.variant()]);
}

// packages/primitives/src/ProgressBar.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface ProgressBarProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  value?: number;
  max?: number;
  label?: ReactNode;
  showValue?: boolean;
  size?: 'sm' | 'md' | 'lg';
  variant?: 'accent' | 'success' | 'warning' | 'danger';
  indeterminate?: boolean;
}

const sizeStyles = {
  sm: 'h-1',
  md: 'h-2',
  lg: 'h-3',
} as const;

const variantStyles = {
  accent: 'bg-accent',
  success: 'bg-emerald-500',
  warning: 'bg-amber-500',
  danger: 'bg-red-500',
} as const;

function classes(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(' ');
}

export function ProgressBar({
  value = 0,
  max = 100,
  label,
  showValue = false,
  size = 'md',
  variant = 'accent',
  indeterminate = false,
  className,
  ...rest
}: ProgressBarProps) {
  const pct = Math.max(0, Math.min(100, (value / max) * 100));
  const display = showValue ? `${Math.round(pct)}%` : null;

  return (
    <div className={classes('flex flex-col gap-1.5', className)} {...rest}>
      {(label || display) && (
        <div className="flex items-center justify-between text-xs text-slate-600">
          <span>{label}</span>
          {display && <span className="font-mono">{display}</span>}
        </div>
      )}
      <div
        role="progressbar"
        aria-valuenow={indeterminate ? undefined : value}
        aria-valuemin={0}
        aria-valuemax={max}
        aria-label={typeof label === 'string' ? label : undefined}
        className={classes('w-full bg-slate-200 rounded-full overflow-hidden', sizeStyles[size])}
      >
        <div
          className={classes(
            'h-full rounded-full transition-[width] duration-300 ease-out',
            variantStyles[variant],
            indeterminate && 'animate-[progress-indeterminate_1.4s_ease-in-out_infinite]',
          )}
          style={indeterminate ? { width: '40%' } : { width: `${pct}%` }}
        />
        {indeterminate && (
          <style>{`
            @keyframes progress-indeterminate {
              0%   { transform: translateX(-100%); }
              100% { transform: translateX(250%); }
            }
          `}</style>
        )}
      </div>
    </div>
  );
}
