// packages/ui-ng/src/lib/submit/submit.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

/**
 * Form submit button — Angular 22 port of `@ferrlabs/ui-react`'s Submit. Mono
 * uppercase, accent-filled, `type="submit"`. `loading` shows a spinner and
 * disables the button; project the label as content.
 */
@Component({
  selector: 'flr-submit',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="submit"
      class="flr-submit mono"
      [class.flr-submit--full]="fullWidth()"
      [disabled]="inactive()"
      [attr.aria-busy]="loading() || null"
    >
      @if (loading()) {
        <span class="flr-submit__spinner" aria-hidden="true"></span>
      }
      <ng-content />
    </button>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-submit {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      height: 40px;
      padding: 0 16px;
      font-family: var(--font-mono);
      font-size: 12px;
      font-weight: 500;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      line-height: 1;
      white-space: nowrap;
      user-select: none;
      color: #fff;
      background: var(--color-accent, var(--color-ink));
      border: 1px solid var(--color-accent, var(--color-ink));
      border-radius: 8px;
      cursor: pointer;
      transition:
        background 160ms ease-out,
        opacity 160ms,
        box-shadow 160ms;
    }
    .flr-submit--full {
      display: flex;
      width: 100%;
    }
    .flr-submit:disabled {
      cursor: not-allowed;
      opacity: 0.55;
    }
    .flr-submit__spinner {
      width: 12px;
      height: 12px;
      border: 1.5px solid #fff;
      border-right-color: transparent;
      border-radius: 50%;
      display: inline-block;
      animation: flr-submit-spin 700ms linear infinite;
    }
    @keyframes flr-submit-spin {
      to {
        transform: rotate(360deg);
      }
    }
  `,
})
export class SubmitComponent {
  readonly loading = input(false);
  readonly fullWidth = input(false);
  readonly disabled = input(false);

  protected readonly inactive = computed(() => this.disabled() || this.loading());
}

// packages/primitives/src/Submit.tsx
import { forwardRef, type ButtonHTMLAttributes, type CSSProperties, type ReactNode } from 'react';

export interface SubmitProps extends Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'type' | 'children'
> {
  loading?: boolean;
  fullWidth?: boolean;
  children: ReactNode;
}

export const Submit = forwardRef<HTMLButtonElement, SubmitProps>(function Submit(
  { loading = false, fullWidth = false, disabled, className, style, children, ...rest },
  ref,
) {
  const isInactive = Boolean(disabled || loading);
  const accent = 'var(--color-accent, var(--color-ink))';

  const baseStyle: CSSProperties = {
    display: fullWidth ? 'flex' : 'inline-flex',
    width: fullWidth ? '100%' : undefined,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 40,
    padding: '0 16px',
    fontFamily: 'var(--font-mono)',
    fontSize: 12,
    fontWeight: 500,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    lineHeight: 1,
    whiteSpace: 'nowrap',
    userSelect: 'none',
    color: '#fff',
    background: accent,
    border: `1px solid ${accent}`,
    borderRadius: 8,
    cursor: isInactive ? 'not-allowed' : 'pointer',
    opacity: isInactive ? 0.55 : 1,
    transition: 'background 160ms ease-out, opacity 160ms, box-shadow 160ms',
    ...style,
  };

  return (
    <button
      ref={ref}
      type="submit"
      className={['mono', className].filter(Boolean).join(' ')}
      style={baseStyle}
      disabled={isInactive}
      aria-busy={loading || undefined}
      {...rest}
    >
      {loading && (
        <span
          aria-hidden
          style={{
            width: 12,
            height: 12,
            border: '1.5px solid #fff',
            borderRightColor: 'transparent',
            borderRadius: '50%',
            display: 'inline-block',
            animation: 'ferrlabs-spin 700ms linear infinite',
          }}
        />
      )}
      {children}
      <style>{`@keyframes ferrlabs-spin { to { transform: rotate(360deg); } }`}</style>
    </button>
  );
});
