// packages/ui-ng/src/lib/avatar/avatar.component.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core';

export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | number;
export type AvatarShape = 'circle' | 'square';

const SIZE_MAP: Record<Exclude<AvatarSize, number>, number> = {
  xs: 20,
  sm: 24,
  md: 28,
  lg: 40,
  xl: 56,
};

@Component({
  selector: 'flr-avatar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (src() && !errored()) {
      <img
        class="flr-avatar__img"
        [src]="src()"
        [alt]="alt() ?? name()"
        [title]="name()"
        [style.width.px]="px()"
        [style.height.px]="px()"
        [style.border-radius.px]="radius()"
        (error)="errored.set(true)"
      />
    } @else {
      <span
        class="flr-avatar__fallback"
        [title]="name()"
        [style.width.px]="px()"
        [style.height.px]="px()"
        [style.border-radius.px]="radius()"
        [style.background]="accent() ?? 'var(--color-rule-strong)'"
        [style.font-size.px]="px() * 0.4"
      >
        {{ initials() }}
      </span>
    }
  `,
  styles: `
    :host {
      display: inline-flex;
      flex-shrink: 0;
      line-height: 0;
    }
    .flr-avatar__img {
      display: block;
      object-fit: cover;
    }
    .flr-avatar__fallback {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      color: #fff;
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-weight: 500;
      user-select: none;
    }
  `,
})
export class AvatarComponent {
  readonly name = input.required<string>();
  readonly src = input<string | null>(null);
  readonly accent = input<string | null>(null);
  readonly size = input<AvatarSize>(28);
  readonly shape = input<AvatarShape>('circle');
  readonly alt = input<string | null>(null);

  protected readonly errored = signal(false);

  protected readonly px = computed(() => {
    const s = this.size();
    return typeof s === 'number' ? s : SIZE_MAP[s];
  });

  protected readonly radius = computed(() =>
    this.shape() === 'circle' ? this.px() / 2 : Math.max(4, this.px() * 0.18),
  );

  protected readonly initials = computed(
    () =>
      this.name()
        .split(' ')
        .map((s) => s[0])
        .filter(Boolean)
        .slice(0, 2)
        .join('')
        .toUpperCase() || '?',
  );
}

// packages/ui/src/react/components/app/Avatar.tsx
import { useState } from 'react';

export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | number;
export type AvatarShape = 'circle' | 'square';

interface Props {
  name: string;
  src?: string | null;
  /** Hex accent for the initials background. Defaults to `--color-rule-strong`. */
  accent?: string;
  /** Number (px) or token (xs=20, sm=24, md=28, lg=40, xl=56). */
  size?: AvatarSize;
  shape?: AvatarShape;
  className?: string;
  alt?: string;
}

const sizeMap: Record<Exclude<AvatarSize, number>, number> = {
  xs: 20,
  sm: 24,
  md: 28,
  lg: 40,
  xl: 56,
};

function resolveSize(size: AvatarSize): number {
  return typeof size === 'number' ? size : sizeMap[size];
}

/**
 * Editorial avatar — image when `src` set, otherwise mono initials over `accent`.
 * Falls back to initials if the image errors. Square or circle.
 */
export function Avatar({ name, src, accent, size = 28, shape = 'circle', className, alt }: Props) {
  const [errored, setErrored] = useState(false);
  const px = resolveSize(size);
  const radius = shape === 'circle' ? px / 2 : Math.max(4, px * 0.18);

  if (src && !errored) {
    return (
      <img
        src={src}
        alt={alt ?? name}
        title={name}
        className={className}
        onError={() => setErrored(true)}
        style={{
          width: px,
          height: px,
          borderRadius: radius,
          display: 'block',
          objectFit: 'cover',
          flexShrink: 0,
        }}
      />
    );
  }

  const initials =
    name
      .split(' ')
      .map((s) => s[0])
      .filter(Boolean)
      .slice(0, 2)
      .join('')
      .toUpperCase() || '?';

  return (
    <span
      className={className}
      title={name}
      style={{
        width: px,
        height: px,
        borderRadius: radius,
        background: accent ?? 'var(--color-rule-strong)',
        color: '#fff',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontFamily: 'var(--font-mono)',
        fontSize: px * 0.4,
        fontWeight: 500,
        flexShrink: 0,
        userSelect: 'none',
      }}
    >
      {initials}
    </span>
  );
}
