// packages/ui/src/react/components/app/SiteCard.tsx
import type { CSSProperties, KeyboardEvent, MouseEvent, ReactNode } from 'react';

export interface SiteCardProps {
  icon: ReactNode;
  label: string;
  meta?: ReactNode;
  onClick?: (e: MouseEvent<HTMLDivElement> | KeyboardEvent<HTMLDivElement>) => void;
  showChevron?: boolean;
  className?: string;
  style?: CSSProperties;
}

export function SiteCard({
  icon,
  label,
  meta,
  onClick,
  showChevron = true,
  className,
  style,
}: SiteCardProps) {
  const interactive = !!onClick;
  return (
    <div
      className={className}
      role={interactive ? 'button' : undefined}
      tabIndex={interactive ? 0 : undefined}
      onClick={interactive ? onClick : undefined}
      onKeyDown={
        interactive
          ? (e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                onClick?.(e);
              }
            }
          : undefined
      }
      style={{
        margin: '8px 12px',
        padding: '10px 12px',
        background: 'var(--color-card, #fff)',
        border: '1px solid var(--color-rule, #e2e8f0)',
        borderRadius: 8,
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        cursor: interactive ? 'pointer' : 'default',
        ...style,
      }}
    >
      {icon}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div
          style={{
            fontSize: 13,
            fontWeight: 600,
            color: 'var(--color-fg, #0f172a)',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
          }}
        >
          {label}
        </div>
        {meta ? (
          <div
            style={{
              fontSize: 11,
              color: 'var(--color-fg-2, #475569)',
              marginTop: 1,
              display: 'flex',
              gap: 6,
              alignItems: 'center',
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
            }}
          >
            {meta}
          </div>
        ) : null}
      </div>
      {showChevron ? (
        <svg
          aria-hidden
          width={12}
          height={12}
          viewBox="0 0 12 12"
          fill="none"
          style={{
            color: 'var(--color-fg-3, #94a3b8)',
            flexShrink: 0,
            display: 'block',
          }}
        >
          <path
            d="M3 4.5L6 7.5L9 4.5"
            stroke="currentColor"
            strokeWidth={1.4}
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      ) : null}
    </div>
  );
}

// packages/ui-ng/src/lib/site-card/site-card.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';

@Component({
  selector: 'flr-site-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      class="flr-sc"
      [class.flr-sc--interactive]="interactive()"
      [attr.role]="interactive() ? 'button' : null"
      [attr.tabindex]="interactive() ? 0 : null"
      (click)="onActivate()"
      (keydown)="onKeydown($event)"
    >
      <span class="flr-sc__icon"><ng-content select="[site-card-icon]" /></span>
      <div class="flr-sc__body">
        <span class="flr-sc__eyebrow mono"><ng-content select="[site-card-eyebrow]" /></span>
        <div class="flr-sc__label">{{ label() }}</div>
        <div class="flr-sc__meta"><ng-content select="[site-card-meta]" /></div>
      </div>
      @if (showChevron()) {
        <svg
          class="flr-sc__chev"
          aria-hidden="true"
          width="12"
          height="12"
          viewBox="0 0 12 12"
          fill="none"
        >
          <path
            d="M3 4.5L6 7.5L9 4.5"
            stroke="currentColor"
            stroke-width="1.4"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      }
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
    .flr-sc {
      margin: 8px 12px;
      padding: 10px 12px;
      background: var(--color-card, #fff);
      border: 1px solid var(--color-rule, #e2e8f0);
      border-radius: 8px;
      display: flex;
      align-items: center;
      gap: 10px;
      cursor: default;
    }
    .flr-sc--interactive {
      cursor: pointer;
    }
    .flr-sc__icon {
      display: inline-flex;
      align-items: center;
      flex-shrink: 0;
    }
    .flr-sc__body {
      flex: 1;
      min-width: 0;
    }
    .flr-sc__eyebrow {
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-size: 9.5px;
      font-weight: 600;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      color: var(--color-ink-3, #94a3b8);
      margin-bottom: 2px;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
      display: block;
    }
    .flr-sc__eyebrow:empty {
      display: none;
    }
    .flr-sc__label {
      font-size: 13px;
      font-weight: 600;
      color: var(--color-ink, #0f172a);
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .flr-sc__meta {
      font-size: 11px;
      color: var(--color-ink-2, #475569);
      margin-top: 1px;
      display: flex;
      gap: 6px;
      align-items: center;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .flr-sc__meta:empty {
      display: none;
    }
    .flr-sc__chev {
      color: var(--color-ink-3, #94a3b8);
      flex-shrink: 0;
      display: block;
    }
  `,
})
export class SiteCardComponent {
  readonly label = input.required<string>();
  readonly showChevron = input(true);
  readonly interactive = input(true);

  readonly select = output<void>();

  protected onActivate(): void {
    if (this.interactive()) this.select.emit();
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.interactive()) return;
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      this.select.emit();
    }
  }
}
