// packages/ui/src/primitives/ProgressBar.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react';

export interface ProgressBarProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  value?: number;
  max?: number;
  label?: ReactNode;
  showValue?: boolean;
  size?: 'sm' | 'md' | 'lg';
  variant?: 'accent' | 'success' | 'warning' | 'danger';
  indeterminate?: boolean;
}

const sizeHeight = { sm: 4, md: 8, lg: 12 } as const;

const variantColor = {
  accent: 'var(--color-accent)',
  success: '#10b981',
  warning: '#f59e0b',
  danger: '#dc2626',
} as const;

export function ProgressBar({
  value = 0,
  max = 100,
  label,
  showValue = false,
  size = 'md',
  variant = 'accent',
  indeterminate = false,
  className,
  style,
  ...rest
}: ProgressBarProps) {
  const pct = Math.max(0, Math.min(100, (value / max) * 100));
  const display = showValue ? `${Math.round(pct)}%` : null;
  const height = sizeHeight[size];
  const fill = variantColor[variant];

  const wrapperStyle: CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    ...style,
  };

  const fillStyle: CSSProperties = indeterminate
    ? {
        height: '100%',
        width: '40%',
        borderRadius: 999,
        background: fill,
        animation: 'progress-indeterminate 1.4s ease-in-out infinite',
      }
    : {
        height: '100%',
        width: `${pct}%`,
        borderRadius: 999,
        background: fill,
        transition: 'width 300ms ease-out',
      };

  return (
    <div className={className} style={wrapperStyle} {...rest}>
      {(label || display) && (
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            fontSize: 12,
            color: 'var(--color-ink-2)',
          }}
        >
          <span>{label}</span>
          {display && (
            <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-ink-3)' }}>
              {display}
            </span>
          )}
        </div>
      )}
      <div
        role="progressbar"
        aria-valuenow={indeterminate ? undefined : value}
        aria-valuemin={0}
        aria-valuemax={max}
        aria-label={typeof label === 'string' ? label : undefined}
        style={{
          width: '100%',
          height,
          background: 'var(--color-rule)',
          borderRadius: 999,
          overflow: 'hidden',
        }}
      >
        <div style={fillStyle} />
        {indeterminate && (
          <style>{`
            @keyframes progress-indeterminate {
              0%   { transform: translateX(-100%); }
              100% { transform: translateX(250%); }
            }
          `}</style>
        )}
      </div>
    </div>
  );
}

// packages/ui-ng/src/lib/progress-bar/progress-bar.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export type ProgressBarSize = 'sm' | 'md' | 'lg';
export type ProgressBarVariant = 'accent' | 'success' | 'warning' | 'danger';

const HEIGHT: Record<ProgressBarSize, string> = {
  sm: '4px',
  md: '8px',
  lg: '12px',
};

const FILL: Record<ProgressBarVariant, string> = {
  accent: 'var(--color-accent)',
  success: '#10b981',
  warning: '#f59e0b',
  danger: '#dc2626',
};

/**
 * Determinate / indeterminate progress bar — Angular 22 port of
 * `@ferrlabs/ui-react`'s ProgressBar. Set `indeterminate` for an animated
 * sweep; otherwise `value`/`max` drive the fill width.
 */
@Component({
  selector: 'flr-progress-bar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flr-progress">
      @if (label() || displayValue()) {
        <div class="flr-progress__meta">
          <span>{{ label() }}</span>
          @if (displayValue(); as d) {
            <span class="flr-progress__value">{{ d }}</span>
          }
        </div>
      }
      <div
        class="flr-progress__track"
        role="progressbar"
        [attr.aria-valuenow]="indeterminate() ? null : value()"
        [attr.aria-valuemin]="0"
        [attr.aria-valuemax]="max()"
        [attr.aria-label]="label()"
        [style.height]="height()"
      >
        <div
          class="flr-progress__fill"
          [class.flr-progress__fill--indeterminate]="indeterminate()"
          [style.background]="fill()"
          [style.width]="indeterminate() ? '40%' : pct() + '%'"
        ></div>
      </div>
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
    .flr-progress {
      display: flex;
      flex-direction: column;
      gap: 6px;
    }
    .flr-progress__meta {
      display: flex;
      align-items: center;
      justify-content: space-between;
      font-size: 12px;
      color: var(--color-ink-2);
    }
    .flr-progress__value {
      font-family: var(--font-mono);
      color: var(--color-ink-3);
    }
    .flr-progress__track {
      width: 100%;
      background: var(--color-rule);
      border-radius: 999px;
      overflow: hidden;
    }
    .flr-progress__fill {
      height: 100%;
      border-radius: 999px;
      transition: width 300ms ease-out;
    }
    .flr-progress__fill--indeterminate {
      transition: none;
      animation: flr-progress-indeterminate 1.4s ease-in-out infinite;
    }
    @keyframes flr-progress-indeterminate {
      0% {
        transform: translateX(-100%);
      }
      100% {
        transform: translateX(250%);
      }
    }
  `,
})
export class ProgressBarComponent {
  readonly value = input(0);
  readonly max = input(100);
  readonly label = input<string | null>(null);
  readonly showValue = input(false);
  readonly size = input<ProgressBarSize>('md');
  readonly variant = input<ProgressBarVariant>('accent');
  readonly indeterminate = input(false);

  protected readonly pct = computed(() =>
    Math.max(0, Math.min(100, (this.value() / this.max()) * 100)),
  );
  protected readonly displayValue = computed(() =>
    this.showValue() ? `${Math.round(this.pct())}%` : null,
  );
  protected readonly height = computed(() => HEIGHT[this.size()]);
  protected readonly fill = computed(() => FILL[this.variant()]);
}
