// packages/primitives/src/Avatar.tsx
import { useState, type HTMLAttributes } from 'react';

export interface AvatarProps extends HTMLAttributes<HTMLSpanElement> {
  name?: string;
  src?: string;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  shape?: 'circle' | 'square';
}

const sizeStyles = {
  xs: 'size-5 text-[10px]',
  sm: 'size-7 text-xs',
  md: 'size-9 text-sm',
  lg: 'size-12 text-base',
  xl: 'size-16 text-lg',
} as const;

function initialsFrom(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return '?';
  if (parts.length === 1) return parts[0]!.slice(0, 2).toUpperCase();
  return (parts[0]![0]! + parts[parts.length - 1]![0]!).toUpperCase();
}

function classes(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(' ');
}

export function Avatar({
  name = '',
  src,
  size = 'md',
  shape = 'circle',
  className,
  ...rest
}: AvatarProps) {
  const [errored, setErrored] = useState(false);
  const showImage = src && !errored;
  const initials = initialsFrom(name || '?');

  return (
    <span
      className={classes(
        'inline-flex items-center justify-center font-medium leading-none select-none bg-slate-200 text-slate-700 overflow-hidden',
        shape === 'circle' ? 'rounded-full' : 'rounded-md',
        sizeStyles[size],
        className,
      )}
      title={name || undefined}
      {...rest}
    >
      {showImage ? (
        <img
          src={src}
          alt={name || ''}
          className="size-full object-cover"
          onError={() => setErrored(true)}
        />
      ) : (
        <span aria-hidden>{initials}</span>
      )}
    </span>
  );
}

// packages/ui-ng/src/lib/avatar/avatar.component.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core';

export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | number;
export type AvatarShape = 'circle' | 'square';

const SIZE_MAP: Record<Exclude<AvatarSize, number>, number> = {
  xs: 20,
  sm: 24,
  md: 28,
  lg: 40,
  xl: 56,
};

@Component({
  selector: 'flr-avatar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (src() && !errored()) {
      <img
        class="flr-avatar__img"
        [src]="src()"
        [alt]="alt() ?? name()"
        [title]="name()"
        [style.width.px]="px()"
        [style.height.px]="px()"
        [style.border-radius.px]="radius()"
        (error)="errored.set(true)"
      />
    } @else {
      <span
        class="flr-avatar__fallback"
        role="img"
        [attr.aria-label]="alt() ?? name()"
        [title]="name()"
        [style.width.px]="px()"
        [style.height.px]="px()"
        [style.border-radius.px]="radius()"
        [style.background]="accent() ?? 'var(--color-avatar-bg, var(--color-ink-2, #475569))'"
        [style.font-size.px]="px() * 0.4"
      >
        {{ initials() }}
      </span>
    }
  `,
  styles: `
    :host {
      display: inline-flex;
      flex-shrink: 0;
      line-height: 0;
    }
    .flr-avatar__img {
      display: block;
      object-fit: cover;
    }
    .flr-avatar__fallback {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      color: #fff;
      font-family: var(--font-mono, 'DM Mono', ui-monospace, monospace);
      font-weight: 500;
      user-select: none;
    }
  `,
})
export class AvatarComponent {
  readonly name = input.required<string>();
  readonly src = input<string | null>(null);
  readonly accent = input<string | null>(null);
  readonly size = input<AvatarSize>(28);
  readonly shape = input<AvatarShape>('circle');
  readonly alt = input<string | null>(null);

  protected readonly errored = signal(false);

  protected readonly px = computed(() => {
    const s = this.size();
    return typeof s === 'number' ? s : SIZE_MAP[s];
  });

  protected readonly radius = computed(() =>
    this.shape() === 'circle' ? this.px() / 2 : Math.max(4, this.px() * 0.18),
  );

  protected readonly initials = computed(
    () =>
      this.name()
        .split(' ')
        .map((s) => s[0])
        .filter(Boolean)
        .slice(0, 2)
        .join('')
        .toUpperCase() || '?',
  );
}
